
namespace ProyectoTallerII
{
    partial class AdminCliente
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AdminCliente));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties53 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties54 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties55 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties56 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.pnl_buscador = new System.Windows.Forms.Panel();
            this.button1 = new System.Windows.Forms.Button();
            this.lbl_user_title = new Bunifu.UI.WinForms.BunifuLabel();
            this.txt_buscar = new Bunifu.UI.WinForms.BunifuTextBox();
            this.dataG_usuarios = new System.Windows.Forms.DataGridView();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.btn_user_elimiar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_user_limpiar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.dtp_user_date_birth = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.lbl_user_date_birth = new Bunifu.UI.WinForms.BunifuLabel();
            this.txt_user_dni = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_user_adress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_user_tel = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btn_user_modificar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txt_user_nombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_user_apellido = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_user_email = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btn_user_agregar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.combo_estado = new System.Windows.Forms.ComboBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.pnl_buscador.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataG_usuarios)).BeginInit();
            this.bunifuPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // pnl_buscador
            // 
            this.pnl_buscador.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.pnl_buscador.Controls.Add(this.button1);
            this.pnl_buscador.Controls.Add(this.lbl_user_title);
            this.pnl_buscador.Controls.Add(this.txt_buscar);
            this.pnl_buscador.Location = new System.Drawing.Point(26, 60);
            this.pnl_buscador.Name = "pnl_buscador";
            this.pnl_buscador.Size = new System.Drawing.Size(741, 63);
            this.pnl_buscador.TabIndex = 21;
            // 
            // button1
            // 
            this.button1.FlatAppearance.BorderSize = 0;
            this.button1.FlatAppearance.MouseOverBackColor = System.Drawing.Color.BlueViolet;
            this.button1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.button1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12.25F);
            this.button1.ForeColor = System.Drawing.Color.White;
            this.button1.Image = global::ProyectoTallerII.Properties.Resources.search_1__2_;
            this.button1.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.button1.Location = new System.Drawing.Point(6, 12);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(43, 37);
            this.button1.TabIndex = 8;
            this.button1.UseVisualStyleBackColor = true;
            // 
            // lbl_user_title
            // 
            this.lbl_user_title.AllowParentOverrides = false;
            this.lbl_user_title.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.lbl_user_title.AutoEllipsis = false;
            this.lbl_user_title.Cursor = System.Windows.Forms.Cursors.Default;
            this.lbl_user_title.CursorType = System.Windows.Forms.Cursors.Default;
            this.lbl_user_title.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.lbl_user_title.Location = new System.Drawing.Point(379, 11);
            this.lbl_user_title.Name = "lbl_user_title";
            this.lbl_user_title.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lbl_user_title.Size = new System.Drawing.Size(67, 21);
            this.lbl_user_title.TabIndex = 9;
            this.lbl_user_title.Text = "CLIENTES";
            this.lbl_user_title.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lbl_user_title.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txt_buscar
            // 
            this.txt_buscar.AcceptsReturn = false;
            this.txt_buscar.AcceptsTab = false;
            this.txt_buscar.AnimationSpeed = 200;
            this.txt_buscar.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_buscar.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_buscar.BackColor = System.Drawing.Color.Transparent;
            this.txt_buscar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_buscar.BackgroundImage")));
            this.txt_buscar.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_buscar.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_buscar.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_buscar.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.txt_buscar.BorderRadius = 20;
            this.txt_buscar.BorderThickness = 2;
            this.txt_buscar.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_buscar.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_buscar.DefaultFont = new System.Drawing.Font("Segoe UI", 10F);
            this.txt_buscar.DefaultText = "";
            this.txt_buscar.FillColor = System.Drawing.SystemColors.ButtonFace;
            this.txt_buscar.HideSelection = true;
            this.txt_buscar.IconLeft = null;
            this.txt_buscar.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_buscar.IconPadding = 10;
            this.txt_buscar.IconRight = null;
            this.txt_buscar.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_buscar.Lines = new string[0];
            this.txt_buscar.Location = new System.Drawing.Point(53, 12);
            this.txt_buscar.MaxLength = 32767;
            this.txt_buscar.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_buscar.Modified = false;
            this.txt_buscar.Multiline = false;
            this.txt_buscar.Name = "txt_buscar";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_buscar.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_buscar.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_buscar.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            stateProperties32.FillColor = System.Drawing.SystemColors.ButtonFace;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_buscar.OnIdleState = stateProperties32;
            this.txt_buscar.Padding = new System.Windows.Forms.Padding(3);
            this.txt_buscar.PasswordChar = '\0';
            this.txt_buscar.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txt_buscar.PlaceholderText = "Buscar...";
            this.txt_buscar.ReadOnly = false;
            this.txt_buscar.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_buscar.SelectedText = "";
            this.txt_buscar.SelectionLength = 0;
            this.txt_buscar.SelectionStart = 0;
            this.txt_buscar.ShortcutsEnabled = true;
            this.txt_buscar.Size = new System.Drawing.Size(248, 37);
            this.txt_buscar.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_buscar.TabIndex = 0;
            this.txt_buscar.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_buscar.TextMarginBottom = 0;
            this.txt_buscar.TextMarginLeft = 3;
            this.txt_buscar.TextMarginTop = 0;
            this.txt_buscar.TextPlaceholder = "Buscar...";
            this.txt_buscar.UseSystemPasswordChar = false;
            this.txt_buscar.WordWrap = true;
            this.txt_buscar.TextChanged += new System.EventHandler(this.txt_buscar_TextChanged);
            this.txt_buscar.KeyUp += new System.Windows.Forms.KeyEventHandler(this.txt_buscar_KeyUp);
            // 
            // dataG_usuarios
            // 
            this.dataG_usuarios.AllowUserToAddRows = false;
            this.dataG_usuarios.AllowUserToDeleteRows = false;
            this.dataG_usuarios.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.dataG_usuarios.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.AllCells;
            this.dataG_usuarios.AutoSizeRowsMode = System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
            this.dataG_usuarios.BackgroundColor = System.Drawing.Color.DarkSlateBlue;
            this.dataG_usuarios.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dataG_usuarios.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dataG_usuarios.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle4.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.Blue;
            dataGridViewCellStyle4.Font = new System.Drawing.Font("Segoe UI Emoji", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle4.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle4.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle4.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dataG_usuarios.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle4;
            this.dataG_usuarios.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dataG_usuarios.EnableHeadersVisualStyles = false;
            this.dataG_usuarios.GridColor = System.Drawing.Color.GreenYellow;
            this.dataG_usuarios.Location = new System.Drawing.Point(-1, 326);
            this.dataG_usuarios.Name = "dataG_usuarios";
            this.dataG_usuarios.ReadOnly = true;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dataG_usuarios.RowHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.dataG_usuarios.RowHeadersVisible = false;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle6.BackColor = System.Drawing.Color.DarkSlateBlue;
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Segoe UI Emoji", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.Color.DeepSkyBlue;
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.Color.Yellow;
            this.dataG_usuarios.RowsDefaultCellStyle = dataGridViewCellStyle6;
            this.dataG_usuarios.Size = new System.Drawing.Size(804, 203);
            this.dataG_usuarios.TabIndex = 23;
            this.dataG_usuarios.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dataG_usuarios_CellClick);
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel1.Controls.Add(this.combo_estado);
            this.bunifuPanel1.Controls.Add(this.btn_user_elimiar);
            this.bunifuPanel1.Controls.Add(this.btn_user_limpiar);
            this.bunifuPanel1.Controls.Add(this.dtp_user_date_birth);
            this.bunifuPanel1.Controls.Add(this.lbl_user_date_birth);
            this.bunifuPanel1.Controls.Add(this.txt_user_dni);
            this.bunifuPanel1.Controls.Add(this.txt_user_adress);
            this.bunifuPanel1.Controls.Add(this.txt_user_tel);
            this.bunifuPanel1.Controls.Add(this.btn_user_modificar);
            this.bunifuPanel1.Controls.Add(this.txt_user_nombre);
            this.bunifuPanel1.Controls.Add(this.txt_user_apellido);
            this.bunifuPanel1.Controls.Add(this.txt_user_email);
            this.bunifuPanel1.Controls.Add(this.btn_user_agregar);
            this.bunifuPanel1.Location = new System.Drawing.Point(32, 129);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(741, 191);
            this.bunifuPanel1.TabIndex = 22;
            // 
            // btn_user_elimiar
            // 
            this.btn_user_elimiar.AllowAnimations = true;
            this.btn_user_elimiar.AllowMouseEffects = true;
            this.btn_user_elimiar.AllowToggling = false;
            this.btn_user_elimiar.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btn_user_elimiar.AnimationSpeed = 200;
            this.btn_user_elimiar.AutoGenerateColors = false;
            this.btn_user_elimiar.AutoRoundBorders = false;
            this.btn_user_elimiar.AutoSizeLeftIcon = true;
            this.btn_user_elimiar.AutoSizeRightIcon = true;
            this.btn_user_elimiar.BackColor = System.Drawing.Color.Transparent;
            this.btn_user_elimiar.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btn_user_elimiar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_user_elimiar.BackgroundImage")));
            this.btn_user_elimiar.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.btn_user_elimiar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_elimiar.ButtonText = "Eliminar";
            this.btn_user_elimiar.ButtonTextMarginLeft = 0;
            this.btn_user_elimiar.ColorContrastOnClick = 45;
            this.btn_user_elimiar.ColorContrastOnHover = 45;
            this.btn_user_elimiar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btn_user_elimiar.CustomizableEdges = borderEdges5;
            this.btn_user_elimiar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_user_elimiar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_user_elimiar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_user_elimiar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_user_elimiar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_user_elimiar.Font = new System.Drawing.Font("Segoe UI Emoji", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_user_elimiar.ForeColor = System.Drawing.Color.White;
            this.btn_user_elimiar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_user_elimiar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_user_elimiar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_user_elimiar.IconMarginLeft = 11;
            this.btn_user_elimiar.IconPadding = 10;
            this.btn_user_elimiar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_user_elimiar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_user_elimiar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_user_elimiar.IconSize = 25;
            this.btn_user_elimiar.IdleBorderColor = System.Drawing.Color.Magenta;
            this.btn_user_elimiar.IdleBorderRadius = 15;
            this.btn_user_elimiar.IdleBorderThickness = 3;
            this.btn_user_elimiar.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btn_user_elimiar.IdleIconLeftImage = global::ProyectoTallerII.Properties.Resources.remove_ico__1_;
            this.btn_user_elimiar.IdleIconRightImage = null;
            this.btn_user_elimiar.IndicateFocus = false;
            this.btn_user_elimiar.Location = new System.Drawing.Point(551, 93);
            this.btn_user_elimiar.Name = "btn_user_elimiar";
            this.btn_user_elimiar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_user_elimiar.OnDisabledState.BorderRadius = 15;
            this.btn_user_elimiar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_elimiar.OnDisabledState.BorderThickness = 3;
            this.btn_user_elimiar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_user_elimiar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_user_elimiar.OnDisabledState.IconLeftImage = null;
            this.btn_user_elimiar.OnDisabledState.IconRightImage = null;
            this.btn_user_elimiar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_user_elimiar.onHoverState.BorderRadius = 15;
            this.btn_user_elimiar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_elimiar.onHoverState.BorderThickness = 3;
            this.btn_user_elimiar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_user_elimiar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_user_elimiar.onHoverState.IconLeftImage = null;
            this.btn_user_elimiar.onHoverState.IconRightImage = null;
            this.btn_user_elimiar.OnIdleState.BorderColor = System.Drawing.Color.Magenta;
            this.btn_user_elimiar.OnIdleState.BorderRadius = 15;
            this.btn_user_elimiar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_elimiar.OnIdleState.BorderThickness = 3;
            this.btn_user_elimiar.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btn_user_elimiar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_user_elimiar.OnIdleState.IconLeftImage = global::ProyectoTallerII.Properties.Resources.remove_ico__1_;
            this.btn_user_elimiar.OnIdleState.IconRightImage = null;
            this.btn_user_elimiar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_user_elimiar.OnPressedState.BorderRadius = 15;
            this.btn_user_elimiar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_elimiar.OnPressedState.BorderThickness = 3;
            this.btn_user_elimiar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_user_elimiar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_user_elimiar.OnPressedState.IconLeftImage = null;
            this.btn_user_elimiar.OnPressedState.IconRightImage = null;
            this.btn_user_elimiar.Size = new System.Drawing.Size(150, 39);
            this.btn_user_elimiar.TabIndex = 24;
            this.btn_user_elimiar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_user_elimiar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_user_elimiar.TextMarginLeft = 0;
            this.btn_user_elimiar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_user_elimiar.UseDefaultRadiusAndThickness = true;
            this.btn_user_elimiar.Click += new System.EventHandler(this.btn_user_elimiar_Click);
            // 
            // btn_user_limpiar
            // 
            this.btn_user_limpiar.AllowAnimations = true;
            this.btn_user_limpiar.AllowMouseEffects = true;
            this.btn_user_limpiar.AllowToggling = false;
            this.btn_user_limpiar.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btn_user_limpiar.AnimationSpeed = 200;
            this.btn_user_limpiar.AutoGenerateColors = false;
            this.btn_user_limpiar.AutoRoundBorders = false;
            this.btn_user_limpiar.AutoSizeLeftIcon = true;
            this.btn_user_limpiar.AutoSizeRightIcon = true;
            this.btn_user_limpiar.BackColor = System.Drawing.Color.Transparent;
            this.btn_user_limpiar.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btn_user_limpiar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_user_limpiar.BackgroundImage")));
            this.btn_user_limpiar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_limpiar.ButtonText = "Limpiar";
            this.btn_user_limpiar.ButtonTextMarginLeft = 0;
            this.btn_user_limpiar.ColorContrastOnClick = 45;
            this.btn_user_limpiar.ColorContrastOnHover = 45;
            this.btn_user_limpiar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btn_user_limpiar.CustomizableEdges = borderEdges6;
            this.btn_user_limpiar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_user_limpiar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_user_limpiar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_user_limpiar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_user_limpiar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_user_limpiar.Font = new System.Drawing.Font("Segoe UI Emoji", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_user_limpiar.ForeColor = System.Drawing.Color.White;
            this.btn_user_limpiar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_user_limpiar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_user_limpiar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_user_limpiar.IconMarginLeft = 11;
            this.btn_user_limpiar.IconPadding = 10;
            this.btn_user_limpiar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_user_limpiar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_user_limpiar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_user_limpiar.IconSize = 25;
            this.btn_user_limpiar.IdleBorderColor = System.Drawing.Color.Magenta;
            this.btn_user_limpiar.IdleBorderRadius = 15;
            this.btn_user_limpiar.IdleBorderThickness = 3;
            this.btn_user_limpiar.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btn_user_limpiar.IdleIconLeftImage = global::ProyectoTallerII.Properties.Resources.eraser__1_;
            this.btn_user_limpiar.IdleIconRightImage = null;
            this.btn_user_limpiar.IndicateFocus = false;
            this.btn_user_limpiar.Location = new System.Drawing.Point(551, 136);
            this.btn_user_limpiar.Name = "btn_user_limpiar";
            this.btn_user_limpiar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_user_limpiar.OnDisabledState.BorderRadius = 15;
            this.btn_user_limpiar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_limpiar.OnDisabledState.BorderThickness = 3;
            this.btn_user_limpiar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_user_limpiar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_user_limpiar.OnDisabledState.IconLeftImage = null;
            this.btn_user_limpiar.OnDisabledState.IconRightImage = null;
            this.btn_user_limpiar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_user_limpiar.onHoverState.BorderRadius = 15;
            this.btn_user_limpiar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_limpiar.onHoverState.BorderThickness = 3;
            this.btn_user_limpiar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_user_limpiar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_user_limpiar.onHoverState.IconLeftImage = null;
            this.btn_user_limpiar.onHoverState.IconRightImage = null;
            this.btn_user_limpiar.OnIdleState.BorderColor = System.Drawing.Color.Magenta;
            this.btn_user_limpiar.OnIdleState.BorderRadius = 15;
            this.btn_user_limpiar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_limpiar.OnIdleState.BorderThickness = 3;
            this.btn_user_limpiar.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btn_user_limpiar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_user_limpiar.OnIdleState.IconLeftImage = global::ProyectoTallerII.Properties.Resources.eraser__1_;
            this.btn_user_limpiar.OnIdleState.IconRightImage = null;
            this.btn_user_limpiar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_user_limpiar.OnPressedState.BorderRadius = 15;
            this.btn_user_limpiar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_limpiar.OnPressedState.BorderThickness = 3;
            this.btn_user_limpiar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_user_limpiar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_user_limpiar.OnPressedState.IconLeftImage = null;
            this.btn_user_limpiar.OnPressedState.IconRightImage = null;
            this.btn_user_limpiar.Size = new System.Drawing.Size(150, 39);
            this.btn_user_limpiar.TabIndex = 23;
            this.btn_user_limpiar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_user_limpiar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_user_limpiar.TextMarginLeft = 0;
            this.btn_user_limpiar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_user_limpiar.UseDefaultRadiusAndThickness = true;
            this.btn_user_limpiar.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // dtp_user_date_birth
            // 
            this.dtp_user_date_birth.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.dtp_user_date_birth.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.dtp_user_date_birth.BorderRadius = 13;
            this.dtp_user_date_birth.CalendarFont = new System.Drawing.Font("Segoe UI Emoji", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dtp_user_date_birth.Color = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.dtp_user_date_birth.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thick;
            this.dtp_user_date_birth.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dtp_user_date_birth.DisabledColor = System.Drawing.Color.Gray;
            this.dtp_user_date_birth.DisplayWeekNumbers = false;
            this.dtp_user_date_birth.DPHeight = 0;
            this.dtp_user_date_birth.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.dtp_user_date_birth.FillDatePicker = false;
            this.dtp_user_date_birth.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.dtp_user_date_birth.ForeColor = System.Drawing.Color.Black;
            this.dtp_user_date_birth.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dtp_user_date_birth.Icon = ((System.Drawing.Image)(resources.GetObject("dtp_user_date_birth.Icon")));
            this.dtp_user_date_birth.IconColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.dtp_user_date_birth.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dtp_user_date_birth.LeftTextMargin = 5;
            this.dtp_user_date_birth.Location = new System.Drawing.Point(385, 91);
            this.dtp_user_date_birth.MinimumSize = new System.Drawing.Size(4, 32);
            this.dtp_user_date_birth.Name = "dtp_user_date_birth";
            this.dtp_user_date_birth.Size = new System.Drawing.Size(97, 32);
            this.dtp_user_date_birth.TabIndex = 7;
            this.dtp_user_date_birth.Value = new System.DateTime(2021, 11, 5, 3, 29, 0, 0);
            // 
            // lbl_user_date_birth
            // 
            this.lbl_user_date_birth.AllowParentOverrides = false;
            this.lbl_user_date_birth.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.lbl_user_date_birth.AutoEllipsis = false;
            this.lbl_user_date_birth.Cursor = System.Windows.Forms.Cursors.Default;
            this.lbl_user_date_birth.CursorType = System.Windows.Forms.Cursors.Default;
            this.lbl_user_date_birth.Font = new System.Drawing.Font("Segoe UI Emoji", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbl_user_date_birth.Location = new System.Drawing.Point(284, 91);
            this.lbl_user_date_birth.Name = "lbl_user_date_birth";
            this.lbl_user_date_birth.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lbl_user_date_birth.Size = new System.Drawing.Size(95, 21);
            this.lbl_user_date_birth.TabIndex = 21;
            this.lbl_user_date_birth.Text = "Fecha de Nac.";
            this.lbl_user_date_birth.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lbl_user_date_birth.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txt_user_dni
            // 
            this.txt_user_dni.AcceptsReturn = false;
            this.txt_user_dni.AcceptsTab = false;
            this.txt_user_dni.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txt_user_dni.AnimationSpeed = 200;
            this.txt_user_dni.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_user_dni.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_user_dni.BackColor = System.Drawing.Color.Transparent;
            this.txt_user_dni.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_user_dni.BackgroundImage")));
            this.txt_user_dni.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_user_dni.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_user_dni.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_user_dni.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.txt_user_dni.BorderRadius = 20;
            this.txt_user_dni.BorderThickness = 2;
            this.txt_user_dni.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_user_dni.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_dni.DefaultFont = new System.Drawing.Font("Segoe UI", 10F);
            this.txt_user_dni.DefaultText = "";
            this.txt_user_dni.FillColor = System.Drawing.SystemColors.ButtonFace;
            this.txt_user_dni.HideSelection = true;
            this.txt_user_dni.IconLeft = null;
            this.txt_user_dni.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_dni.IconPadding = 10;
            this.txt_user_dni.IconRight = null;
            this.txt_user_dni.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_dni.Lines = new string[0];
            this.txt_user_dni.Location = new System.Drawing.Point(50, 91);
            this.txt_user_dni.MaxLength = 8;
            this.txt_user_dni.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_user_dni.Modified = false;
            this.txt_user_dni.Multiline = false;
            this.txt_user_dni.Name = "txt_user_dni";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_dni.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_user_dni.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_dni.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            stateProperties36.FillColor = System.Drawing.SystemColors.ButtonFace;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_dni.OnIdleState = stateProperties36;
            this.txt_user_dni.Padding = new System.Windows.Forms.Padding(3);
            this.txt_user_dni.PasswordChar = '\0';
            this.txt_user_dni.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txt_user_dni.PlaceholderText = "DNI";
            this.txt_user_dni.ReadOnly = false;
            this.txt_user_dni.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_user_dni.SelectedText = "";
            this.txt_user_dni.SelectionLength = 0;
            this.txt_user_dni.SelectionStart = 0;
            this.txt_user_dni.ShortcutsEnabled = true;
            this.txt_user_dni.Size = new System.Drawing.Size(198, 38);
            this.txt_user_dni.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_user_dni.TabIndex = 3;
            this.txt_user_dni.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_user_dni.TextMarginBottom = 0;
            this.txt_user_dni.TextMarginLeft = 3;
            this.txt_user_dni.TextMarginTop = 0;
            this.txt_user_dni.TextPlaceholder = "DNI";
            this.txt_user_dni.UseSystemPasswordChar = false;
            this.txt_user_dni.WordWrap = true;
            this.txt_user_dni.TextChanged += new System.EventHandler(this.txt_user_dni_TextChanged);
            this.txt_user_dni.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_user_dni_KeyPress);
            // 
            // txt_user_adress
            // 
            this.txt_user_adress.AcceptsReturn = false;
            this.txt_user_adress.AcceptsTab = false;
            this.txt_user_adress.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txt_user_adress.AnimationSpeed = 200;
            this.txt_user_adress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_user_adress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_user_adress.BackColor = System.Drawing.Color.Transparent;
            this.txt_user_adress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_user_adress.BackgroundImage")));
            this.txt_user_adress.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_user_adress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_user_adress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_user_adress.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.txt_user_adress.BorderRadius = 20;
            this.txt_user_adress.BorderThickness = 2;
            this.txt_user_adress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_user_adress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_adress.DefaultFont = new System.Drawing.Font("Segoe UI", 10F);
            this.txt_user_adress.DefaultText = "";
            this.txt_user_adress.FillColor = System.Drawing.SystemColors.ButtonFace;
            this.txt_user_adress.HideSelection = true;
            this.txt_user_adress.IconLeft = null;
            this.txt_user_adress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_adress.IconPadding = 10;
            this.txt_user_adress.IconRight = null;
            this.txt_user_adress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_adress.Lines = new string[0];
            this.txt_user_adress.Location = new System.Drawing.Point(284, 47);
            this.txt_user_adress.MaxLength = 32767;
            this.txt_user_adress.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_user_adress.Modified = false;
            this.txt_user_adress.Multiline = false;
            this.txt_user_adress.Name = "txt_user_adress";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_adress.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_user_adress.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_adress.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            stateProperties40.FillColor = System.Drawing.SystemColors.ButtonFace;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_adress.OnIdleState = stateProperties40;
            this.txt_user_adress.Padding = new System.Windows.Forms.Padding(3);
            this.txt_user_adress.PasswordChar = '\0';
            this.txt_user_adress.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txt_user_adress.PlaceholderText = "Dirección";
            this.txt_user_adress.ReadOnly = false;
            this.txt_user_adress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_user_adress.SelectedText = "";
            this.txt_user_adress.SelectionLength = 0;
            this.txt_user_adress.SelectionStart = 0;
            this.txt_user_adress.ShortcutsEnabled = true;
            this.txt_user_adress.Size = new System.Drawing.Size(198, 38);
            this.txt_user_adress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_user_adress.TabIndex = 6;
            this.txt_user_adress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_user_adress.TextMarginBottom = 0;
            this.txt_user_adress.TextMarginLeft = 3;
            this.txt_user_adress.TextMarginTop = 0;
            this.txt_user_adress.TextPlaceholder = "Dirección";
            this.txt_user_adress.UseSystemPasswordChar = false;
            this.txt_user_adress.WordWrap = true;
            // 
            // txt_user_tel
            // 
            this.txt_user_tel.AcceptsReturn = false;
            this.txt_user_tel.AcceptsTab = false;
            this.txt_user_tel.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txt_user_tel.AnimationSpeed = 200;
            this.txt_user_tel.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_user_tel.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_user_tel.BackColor = System.Drawing.Color.Transparent;
            this.txt_user_tel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_user_tel.BackgroundImage")));
            this.txt_user_tel.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_user_tel.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_user_tel.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_user_tel.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.txt_user_tel.BorderRadius = 20;
            this.txt_user_tel.BorderThickness = 2;
            this.txt_user_tel.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_user_tel.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_tel.DefaultFont = new System.Drawing.Font("Segoe UI", 10F);
            this.txt_user_tel.DefaultText = "";
            this.txt_user_tel.FillColor = System.Drawing.SystemColors.ButtonFace;
            this.txt_user_tel.HideSelection = true;
            this.txt_user_tel.IconLeft = null;
            this.txt_user_tel.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_tel.IconPadding = 10;
            this.txt_user_tel.IconRight = null;
            this.txt_user_tel.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_tel.Lines = new string[0];
            this.txt_user_tel.Location = new System.Drawing.Point(284, 3);
            this.txt_user_tel.MaxLength = 32767;
            this.txt_user_tel.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_user_tel.Modified = false;
            this.txt_user_tel.Multiline = false;
            this.txt_user_tel.Name = "txt_user_tel";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_tel.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_user_tel.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_tel.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            stateProperties44.FillColor = System.Drawing.SystemColors.ButtonFace;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_tel.OnIdleState = stateProperties44;
            this.txt_user_tel.Padding = new System.Windows.Forms.Padding(3);
            this.txt_user_tel.PasswordChar = '\0';
            this.txt_user_tel.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txt_user_tel.PlaceholderText = "Teléfono";
            this.txt_user_tel.ReadOnly = false;
            this.txt_user_tel.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_user_tel.SelectedText = "";
            this.txt_user_tel.SelectionLength = 0;
            this.txt_user_tel.SelectionStart = 0;
            this.txt_user_tel.ShortcutsEnabled = true;
            this.txt_user_tel.Size = new System.Drawing.Size(198, 38);
            this.txt_user_tel.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_user_tel.TabIndex = 5;
            this.txt_user_tel.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_user_tel.TextMarginBottom = 0;
            this.txt_user_tel.TextMarginLeft = 3;
            this.txt_user_tel.TextMarginTop = 0;
            this.txt_user_tel.TextPlaceholder = "Teléfono";
            this.txt_user_tel.UseSystemPasswordChar = false;
            this.txt_user_tel.WordWrap = true;
            this.txt_user_tel.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_user_tel_KeyPress);
            // 
            // btn_user_modificar
            // 
            this.btn_user_modificar.AllowAnimations = true;
            this.btn_user_modificar.AllowMouseEffects = true;
            this.btn_user_modificar.AllowToggling = false;
            this.btn_user_modificar.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btn_user_modificar.AnimationSpeed = 200;
            this.btn_user_modificar.AutoGenerateColors = false;
            this.btn_user_modificar.AutoRoundBorders = false;
            this.btn_user_modificar.AutoSizeLeftIcon = true;
            this.btn_user_modificar.AutoSizeRightIcon = true;
            this.btn_user_modificar.BackColor = System.Drawing.Color.Transparent;
            this.btn_user_modificar.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btn_user_modificar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_user_modificar.BackgroundImage")));
            this.btn_user_modificar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_modificar.ButtonText = "Modificar";
            this.btn_user_modificar.ButtonTextMarginLeft = 0;
            this.btn_user_modificar.ColorContrastOnClick = 45;
            this.btn_user_modificar.ColorContrastOnHover = 45;
            this.btn_user_modificar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btn_user_modificar.CustomizableEdges = borderEdges7;
            this.btn_user_modificar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_user_modificar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_user_modificar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_user_modificar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_user_modificar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_user_modificar.Font = new System.Drawing.Font("Segoe UI Emoji", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_user_modificar.ForeColor = System.Drawing.Color.White;
            this.btn_user_modificar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_user_modificar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_user_modificar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_user_modificar.IconMarginLeft = 11;
            this.btn_user_modificar.IconPadding = 10;
            this.btn_user_modificar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_user_modificar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_user_modificar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_user_modificar.IconSize = 25;
            this.btn_user_modificar.IdleBorderColor = System.Drawing.Color.Magenta;
            this.btn_user_modificar.IdleBorderRadius = 15;
            this.btn_user_modificar.IdleBorderThickness = 3;
            this.btn_user_modificar.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btn_user_modificar.IdleIconLeftImage = global::ProyectoTallerII.Properties.Resources.ui_settings__1_;
            this.btn_user_modificar.IdleIconRightImage = null;
            this.btn_user_modificar.IndicateFocus = false;
            this.btn_user_modificar.Location = new System.Drawing.Point(551, 48);
            this.btn_user_modificar.Name = "btn_user_modificar";
            this.btn_user_modificar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_user_modificar.OnDisabledState.BorderRadius = 15;
            this.btn_user_modificar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_modificar.OnDisabledState.BorderThickness = 3;
            this.btn_user_modificar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_user_modificar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_user_modificar.OnDisabledState.IconLeftImage = null;
            this.btn_user_modificar.OnDisabledState.IconRightImage = null;
            this.btn_user_modificar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_user_modificar.onHoverState.BorderRadius = 15;
            this.btn_user_modificar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_modificar.onHoverState.BorderThickness = 3;
            this.btn_user_modificar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_user_modificar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_user_modificar.onHoverState.IconLeftImage = null;
            this.btn_user_modificar.onHoverState.IconRightImage = null;
            this.btn_user_modificar.OnIdleState.BorderColor = System.Drawing.Color.Magenta;
            this.btn_user_modificar.OnIdleState.BorderRadius = 15;
            this.btn_user_modificar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_modificar.OnIdleState.BorderThickness = 3;
            this.btn_user_modificar.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btn_user_modificar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_user_modificar.OnIdleState.IconLeftImage = global::ProyectoTallerII.Properties.Resources.ui_settings__1_;
            this.btn_user_modificar.OnIdleState.IconRightImage = null;
            this.btn_user_modificar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_user_modificar.OnPressedState.BorderRadius = 15;
            this.btn_user_modificar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_modificar.OnPressedState.BorderThickness = 3;
            this.btn_user_modificar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_user_modificar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_user_modificar.OnPressedState.IconLeftImage = null;
            this.btn_user_modificar.OnPressedState.IconRightImage = null;
            this.btn_user_modificar.Size = new System.Drawing.Size(150, 39);
            this.btn_user_modificar.TabIndex = 14;
            this.btn_user_modificar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_user_modificar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_user_modificar.TextMarginLeft = 0;
            this.btn_user_modificar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_user_modificar.UseDefaultRadiusAndThickness = true;
            this.btn_user_modificar.Click += new System.EventHandler(this.btn_user_modificar_Click);
            // 
            // txt_user_nombre
            // 
            this.txt_user_nombre.AcceptsReturn = false;
            this.txt_user_nombre.AcceptsTab = false;
            this.txt_user_nombre.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txt_user_nombre.AnimationSpeed = 200;
            this.txt_user_nombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_user_nombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_user_nombre.BackColor = System.Drawing.Color.Transparent;
            this.txt_user_nombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_user_nombre.BackgroundImage")));
            this.txt_user_nombre.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_user_nombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_user_nombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_user_nombre.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.txt_user_nombre.BorderRadius = 20;
            this.txt_user_nombre.BorderThickness = 2;
            this.txt_user_nombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_user_nombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_nombre.DefaultFont = new System.Drawing.Font("Segoe UI", 10F);
            this.txt_user_nombre.DefaultText = "";
            this.txt_user_nombre.FillColor = System.Drawing.SystemColors.ButtonFace;
            this.txt_user_nombre.HideSelection = true;
            this.txt_user_nombre.IconLeft = null;
            this.txt_user_nombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_nombre.IconPadding = 10;
            this.txt_user_nombre.IconRight = null;
            this.txt_user_nombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_nombre.Lines = new string[0];
            this.txt_user_nombre.Location = new System.Drawing.Point(50, 3);
            this.txt_user_nombre.MaxLength = 32767;
            this.txt_user_nombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_user_nombre.Modified = false;
            this.txt_user_nombre.Multiline = false;
            this.txt_user_nombre.Name = "txt_user_nombre";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_nombre.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_user_nombre.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_nombre.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            stateProperties48.FillColor = System.Drawing.SystemColors.ButtonFace;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_nombre.OnIdleState = stateProperties48;
            this.txt_user_nombre.Padding = new System.Windows.Forms.Padding(3);
            this.txt_user_nombre.PasswordChar = '\0';
            this.txt_user_nombre.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txt_user_nombre.PlaceholderText = "Nombre";
            this.txt_user_nombre.ReadOnly = false;
            this.txt_user_nombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_user_nombre.SelectedText = "";
            this.txt_user_nombre.SelectionLength = 0;
            this.txt_user_nombre.SelectionStart = 0;
            this.txt_user_nombre.ShortcutsEnabled = true;
            this.txt_user_nombre.Size = new System.Drawing.Size(198, 38);
            this.txt_user_nombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_user_nombre.TabIndex = 1;
            this.txt_user_nombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_user_nombre.TextMarginBottom = 0;
            this.txt_user_nombre.TextMarginLeft = 3;
            this.txt_user_nombre.TextMarginTop = 0;
            this.txt_user_nombre.TextPlaceholder = "Nombre";
            this.txt_user_nombre.UseSystemPasswordChar = false;
            this.txt_user_nombre.WordWrap = true;
            this.txt_user_nombre.TextChange += new System.EventHandler(this.txt_user_nombre_TextChange);
            this.txt_user_nombre.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_user_nombre_KeyPress);
            // 
            // txt_user_apellido
            // 
            this.txt_user_apellido.AcceptsReturn = false;
            this.txt_user_apellido.AcceptsTab = false;
            this.txt_user_apellido.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txt_user_apellido.AnimationSpeed = 200;
            this.txt_user_apellido.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_user_apellido.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_user_apellido.BackColor = System.Drawing.Color.Transparent;
            this.txt_user_apellido.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_user_apellido.BackgroundImage")));
            this.txt_user_apellido.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_user_apellido.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_user_apellido.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_user_apellido.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.txt_user_apellido.BorderRadius = 20;
            this.txt_user_apellido.BorderThickness = 2;
            this.txt_user_apellido.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_user_apellido.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_apellido.DefaultFont = new System.Drawing.Font("Segoe UI", 10F);
            this.txt_user_apellido.DefaultText = "";
            this.txt_user_apellido.FillColor = System.Drawing.SystemColors.ButtonFace;
            this.txt_user_apellido.HideSelection = true;
            this.txt_user_apellido.IconLeft = null;
            this.txt_user_apellido.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_apellido.IconPadding = 10;
            this.txt_user_apellido.IconRight = null;
            this.txt_user_apellido.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_apellido.Lines = new string[0];
            this.txt_user_apellido.Location = new System.Drawing.Point(50, 47);
            this.txt_user_apellido.MaxLength = 32767;
            this.txt_user_apellido.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_user_apellido.Modified = false;
            this.txt_user_apellido.Multiline = false;
            this.txt_user_apellido.Name = "txt_user_apellido";
            stateProperties49.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties49.FillColor = System.Drawing.Color.Empty;
            stateProperties49.ForeColor = System.Drawing.Color.Empty;
            stateProperties49.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_apellido.OnActiveState = stateProperties49;
            stateProperties50.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties50.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties50.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties50.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_user_apellido.OnDisabledState = stateProperties50;
            stateProperties51.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties51.FillColor = System.Drawing.Color.Empty;
            stateProperties51.ForeColor = System.Drawing.Color.Empty;
            stateProperties51.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_apellido.OnHoverState = stateProperties51;
            stateProperties52.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            stateProperties52.FillColor = System.Drawing.SystemColors.ButtonFace;
            stateProperties52.ForeColor = System.Drawing.Color.Empty;
            stateProperties52.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_apellido.OnIdleState = stateProperties52;
            this.txt_user_apellido.Padding = new System.Windows.Forms.Padding(3);
            this.txt_user_apellido.PasswordChar = '\0';
            this.txt_user_apellido.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txt_user_apellido.PlaceholderText = "Apellido";
            this.txt_user_apellido.ReadOnly = false;
            this.txt_user_apellido.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_user_apellido.SelectedText = "";
            this.txt_user_apellido.SelectionLength = 0;
            this.txt_user_apellido.SelectionStart = 0;
            this.txt_user_apellido.ShortcutsEnabled = true;
            this.txt_user_apellido.Size = new System.Drawing.Size(198, 38);
            this.txt_user_apellido.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_user_apellido.TabIndex = 2;
            this.txt_user_apellido.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_user_apellido.TextMarginBottom = 0;
            this.txt_user_apellido.TextMarginLeft = 3;
            this.txt_user_apellido.TextMarginTop = 0;
            this.txt_user_apellido.TextPlaceholder = "Apellido";
            this.txt_user_apellido.UseSystemPasswordChar = false;
            this.txt_user_apellido.WordWrap = true;
            this.txt_user_apellido.TextChanged += new System.EventHandler(this.txt_user_apellido_TextChanged);
            this.txt_user_apellido.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_user_apellido_KeyPress);
            // 
            // txt_user_email
            // 
            this.txt_user_email.AcceptsReturn = false;
            this.txt_user_email.AcceptsTab = false;
            this.txt_user_email.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txt_user_email.AnimationSpeed = 200;
            this.txt_user_email.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_user_email.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_user_email.BackColor = System.Drawing.Color.Transparent;
            this.txt_user_email.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_user_email.BackgroundImage")));
            this.txt_user_email.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_user_email.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_user_email.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_user_email.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.txt_user_email.BorderRadius = 20;
            this.txt_user_email.BorderThickness = 2;
            this.txt_user_email.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_user_email.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_email.DefaultFont = new System.Drawing.Font("Segoe UI", 10F);
            this.txt_user_email.DefaultText = "";
            this.txt_user_email.FillColor = System.Drawing.SystemColors.ButtonFace;
            this.txt_user_email.HideSelection = true;
            this.txt_user_email.IconLeft = null;
            this.txt_user_email.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_email.IconPadding = 10;
            this.txt_user_email.IconRight = null;
            this.txt_user_email.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_email.Lines = new string[0];
            this.txt_user_email.Location = new System.Drawing.Point(50, 135);
            this.txt_user_email.MaxLength = 32767;
            this.txt_user_email.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_user_email.Modified = false;
            this.txt_user_email.Multiline = false;
            this.txt_user_email.Name = "txt_user_email";
            stateProperties53.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties53.FillColor = System.Drawing.Color.Empty;
            stateProperties53.ForeColor = System.Drawing.Color.Empty;
            stateProperties53.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_email.OnActiveState = stateProperties53;
            stateProperties54.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties54.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties54.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties54.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_user_email.OnDisabledState = stateProperties54;
            stateProperties55.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties55.FillColor = System.Drawing.Color.Empty;
            stateProperties55.ForeColor = System.Drawing.Color.Empty;
            stateProperties55.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_email.OnHoverState = stateProperties55;
            stateProperties56.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            stateProperties56.FillColor = System.Drawing.SystemColors.ButtonFace;
            stateProperties56.ForeColor = System.Drawing.Color.Empty;
            stateProperties56.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_email.OnIdleState = stateProperties56;
            this.txt_user_email.Padding = new System.Windows.Forms.Padding(3);
            this.txt_user_email.PasswordChar = '\0';
            this.txt_user_email.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txt_user_email.PlaceholderText = "E-mail";
            this.txt_user_email.ReadOnly = false;
            this.txt_user_email.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_user_email.SelectedText = "";
            this.txt_user_email.SelectionLength = 0;
            this.txt_user_email.SelectionStart = 0;
            this.txt_user_email.ShortcutsEnabled = true;
            this.txt_user_email.Size = new System.Drawing.Size(198, 38);
            this.txt_user_email.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_user_email.TabIndex = 4;
            this.txt_user_email.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_user_email.TextMarginBottom = 0;
            this.txt_user_email.TextMarginLeft = 3;
            this.txt_user_email.TextMarginTop = 0;
            this.txt_user_email.TextPlaceholder = "E-mail";
            this.txt_user_email.UseSystemPasswordChar = false;
            this.txt_user_email.WordWrap = true;
            this.txt_user_email.TextChanged += new System.EventHandler(this.txt_user_email_TextChanged);
            this.txt_user_email.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_user_email_KeyPress);
            // 
            // btn_user_agregar
            // 
            this.btn_user_agregar.AllowAnimations = true;
            this.btn_user_agregar.AllowMouseEffects = true;
            this.btn_user_agregar.AllowToggling = false;
            this.btn_user_agregar.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btn_user_agregar.AnimationSpeed = 200;
            this.btn_user_agregar.AutoGenerateColors = false;
            this.btn_user_agregar.AutoRoundBorders = false;
            this.btn_user_agregar.AutoSizeLeftIcon = true;
            this.btn_user_agregar.AutoSizeRightIcon = true;
            this.btn_user_agregar.BackColor = System.Drawing.Color.Transparent;
            this.btn_user_agregar.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btn_user_agregar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_user_agregar.BackgroundImage")));
            this.btn_user_agregar.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.btn_user_agregar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_agregar.ButtonText = "Guardar";
            this.btn_user_agregar.ButtonTextMarginLeft = 0;
            this.btn_user_agregar.ColorContrastOnClick = 45;
            this.btn_user_agregar.ColorContrastOnHover = 45;
            this.btn_user_agregar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btn_user_agregar.CustomizableEdges = borderEdges8;
            this.btn_user_agregar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_user_agregar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_user_agregar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_user_agregar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_user_agregar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_user_agregar.Font = new System.Drawing.Font("Segoe UI Emoji", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_user_agregar.ForeColor = System.Drawing.Color.White;
            this.btn_user_agregar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_user_agregar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_user_agregar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_user_agregar.IconMarginLeft = 11;
            this.btn_user_agregar.IconPadding = 10;
            this.btn_user_agregar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_user_agregar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_user_agregar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_user_agregar.IconSize = 25;
            this.btn_user_agregar.IdleBorderColor = System.Drawing.Color.Magenta;
            this.btn_user_agregar.IdleBorderRadius = 15;
            this.btn_user_agregar.IdleBorderThickness = 3;
            this.btn_user_agregar.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btn_user_agregar.IdleIconLeftImage = global::ProyectoTallerII.Properties.Resources.save__1_;
            this.btn_user_agregar.IdleIconRightImage = null;
            this.btn_user_agregar.IndicateFocus = false;
            this.btn_user_agregar.Location = new System.Drawing.Point(551, 3);
            this.btn_user_agregar.Name = "btn_user_agregar";
            this.btn_user_agregar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_user_agregar.OnDisabledState.BorderRadius = 15;
            this.btn_user_agregar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_agregar.OnDisabledState.BorderThickness = 3;
            this.btn_user_agregar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_user_agregar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_user_agregar.OnDisabledState.IconLeftImage = null;
            this.btn_user_agregar.OnDisabledState.IconRightImage = null;
            this.btn_user_agregar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_user_agregar.onHoverState.BorderRadius = 15;
            this.btn_user_agregar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_agregar.onHoverState.BorderThickness = 3;
            this.btn_user_agregar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_user_agregar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_user_agregar.onHoverState.IconLeftImage = null;
            this.btn_user_agregar.onHoverState.IconRightImage = null;
            this.btn_user_agregar.OnIdleState.BorderColor = System.Drawing.Color.Magenta;
            this.btn_user_agregar.OnIdleState.BorderRadius = 15;
            this.btn_user_agregar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_agregar.OnIdleState.BorderThickness = 3;
            this.btn_user_agregar.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btn_user_agregar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_user_agregar.OnIdleState.IconLeftImage = global::ProyectoTallerII.Properties.Resources.save__1_;
            this.btn_user_agregar.OnIdleState.IconRightImage = null;
            this.btn_user_agregar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_user_agregar.OnPressedState.BorderRadius = 15;
            this.btn_user_agregar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_agregar.OnPressedState.BorderThickness = 3;
            this.btn_user_agregar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_user_agregar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_user_agregar.OnPressedState.IconLeftImage = null;
            this.btn_user_agregar.OnPressedState.IconRightImage = null;
            this.btn_user_agregar.Size = new System.Drawing.Size(150, 39);
            this.btn_user_agregar.TabIndex = 11;
            this.btn_user_agregar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_user_agregar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_user_agregar.TextMarginLeft = 0;
            this.btn_user_agregar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_user_agregar.UseDefaultRadiusAndThickness = true;
            this.btn_user_agregar.Click += new System.EventHandler(this.btn_user_agregar_Click);
            // 
            // combo_estado
            // 
            this.combo_estado.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.combo_estado.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.combo_estado.Cursor = System.Windows.Forms.Cursors.Hand;
            this.combo_estado.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F);
            this.combo_estado.FormattingEnabled = true;
            this.combo_estado.Items.AddRange(new object[] {
            "True",
            "False"});
            this.combo_estado.Location = new System.Drawing.Point(373, 135);
            this.combo_estado.Name = "combo_estado";
            this.combo_estado.Size = new System.Drawing.Size(109, 28);
            this.combo_estado.TabIndex = 25;
            this.combo_estado.Text = "seleccionar";
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI Emoji", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.Location = new System.Drawing.Point(284, 142);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(46, 21);
            this.bunifuLabel1.TabIndex = 26;
            this.bunifuLabel1.Text = "Activo:";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // AdminCliente
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(802, 527);
            this.Controls.Add(this.dataG_usuarios);
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.pnl_buscador);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "AdminCliente";
            this.Text = "Form_vendedor_clientes";
            this.Load += new System.EventHandler(this.Form_vendedor_clientes_Load);
            this.pnl_buscador.ResumeLayout(false);
            this.pnl_buscador.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataG_usuarios)).EndInit();
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel pnl_buscador;
        private System.Windows.Forms.Button button1;
        private Bunifu.UI.WinForms.BunifuLabel lbl_user_title;
        private Bunifu.UI.WinForms.BunifuTextBox txt_buscar;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_user_limpiar;
        private Bunifu.UI.WinForms.BunifuDatePicker dtp_user_date_birth;
        private Bunifu.UI.WinForms.BunifuLabel lbl_user_date_birth;
        private Bunifu.UI.WinForms.BunifuTextBox txt_user_dni;
        private Bunifu.UI.WinForms.BunifuTextBox txt_user_adress;
        private Bunifu.UI.WinForms.BunifuTextBox txt_user_tel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_user_modificar;
        private Bunifu.UI.WinForms.BunifuTextBox txt_user_nombre;
        private Bunifu.UI.WinForms.BunifuTextBox txt_user_apellido;
        private Bunifu.UI.WinForms.BunifuTextBox txt_user_email;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_user_agregar;
        private System.Windows.Forms.DataGridView dataG_usuarios;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_user_elimiar;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private System.Windows.Forms.ComboBox combo_estado;
    }
}