
namespace ProyectoTallerII
{
    partial class AdminCliente
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AdminCliente));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            this.pnl_buscador = new System.Windows.Forms.Panel();
            this.button1 = new System.Windows.Forms.Button();
            this.lbl_pbuckup = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.lbl_username = new Bunifu.UI.WinForms.BunifuLabel();
            this.lbl_user_title = new Bunifu.UI.WinForms.BunifuLabel();
            this.txt_buscar = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.btn_user_elimiar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_user_limpiar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.dtp_user_date_birth = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.lbl_user_date_birth = new Bunifu.UI.WinForms.BunifuLabel();
            this.txt_user_dni = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_user_adress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_user_tel = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btn_user_modificar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txt_user_nombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_user_apellido = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_user_email = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btn_user_agregar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.dataG_usuarios = new System.Windows.Forms.DataGridView();
            this.pnl_buscador.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.lbl_pbuckup)).BeginInit();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataG_usuarios)).BeginInit();
            this.SuspendLayout();
            // 
            // pnl_buscador
            // 
            this.pnl_buscador.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.pnl_buscador.Controls.Add(this.button1);
            this.pnl_buscador.Controls.Add(this.lbl_pbuckup);
            this.pnl_buscador.Controls.Add(this.lbl_username);
            this.pnl_buscador.Controls.Add(this.lbl_user_title);
            this.pnl_buscador.Controls.Add(this.txt_buscar);
            this.pnl_buscador.Location = new System.Drawing.Point(26, 60);
            this.pnl_buscador.Name = "pnl_buscador";
            this.pnl_buscador.Size = new System.Drawing.Size(741, 63);
            this.pnl_buscador.TabIndex = 21;
            // 
            // button1
            // 
            this.button1.FlatAppearance.BorderSize = 0;
            this.button1.FlatAppearance.MouseOverBackColor = System.Drawing.Color.BlueViolet;
            this.button1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.button1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12.25F);
            this.button1.ForeColor = System.Drawing.Color.White;
            this.button1.Image = global::ProyectoTallerII.Properties.Resources.search_1__2_;
            this.button1.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.button1.Location = new System.Drawing.Point(6, 12);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(43, 37);
            this.button1.TabIndex = 8;
            this.button1.UseVisualStyleBackColor = true;
            // 
            // lbl_pbuckup
            // 
            this.lbl_pbuckup.AllowFocused = false;
            this.lbl_pbuckup.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.lbl_pbuckup.AutoSizeHeight = true;
            this.lbl_pbuckup.BorderRadius = 24;
            this.lbl_pbuckup.Image = ((System.Drawing.Image)(resources.GetObject("lbl_pbuckup.Image")));
            this.lbl_pbuckup.IsCircle = true;
            this.lbl_pbuckup.Location = new System.Drawing.Point(680, 7);
            this.lbl_pbuckup.Name = "lbl_pbuckup";
            this.lbl_pbuckup.Size = new System.Drawing.Size(49, 49);
            this.lbl_pbuckup.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.lbl_pbuckup.TabIndex = 3;
            this.lbl_pbuckup.TabStop = false;
            this.lbl_pbuckup.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // lbl_username
            // 
            this.lbl_username.AllowParentOverrides = false;
            this.lbl_username.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.lbl_username.AutoEllipsis = false;
            this.lbl_username.Cursor = System.Windows.Forms.Cursors.Default;
            this.lbl_username.CursorType = System.Windows.Forms.Cursors.Default;
            this.lbl_username.Font = new System.Drawing.Font("Segoe UI", 11F);
            this.lbl_username.Location = new System.Drawing.Point(544, 12);
            this.lbl_username.Name = "lbl_username";
            this.lbl_username.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lbl_username.Size = new System.Drawing.Size(130, 20);
            this.lbl_username.TabIndex = 2;
            this.lbl_username.Text = "Fernando Caballero";
            this.lbl_username.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lbl_username.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lbl_user_title
            // 
            this.lbl_user_title.AllowParentOverrides = false;
            this.lbl_user_title.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.lbl_user_title.AutoEllipsis = false;
            this.lbl_user_title.Cursor = System.Windows.Forms.Cursors.Default;
            this.lbl_user_title.CursorType = System.Windows.Forms.Cursors.Default;
            this.lbl_user_title.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.lbl_user_title.Location = new System.Drawing.Point(379, 11);
            this.lbl_user_title.Name = "lbl_user_title";
            this.lbl_user_title.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lbl_user_title.Size = new System.Drawing.Size(67, 21);
            this.lbl_user_title.TabIndex = 9;
            this.lbl_user_title.Text = "CLIENTES";
            this.lbl_user_title.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lbl_user_title.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txt_buscar
            // 
            this.txt_buscar.AcceptsReturn = false;
            this.txt_buscar.AcceptsTab = false;
            this.txt_buscar.AnimationSpeed = 200;
            this.txt_buscar.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_buscar.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_buscar.BackColor = System.Drawing.Color.Transparent;
            this.txt_buscar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_buscar.BackgroundImage")));
            this.txt_buscar.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_buscar.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_buscar.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_buscar.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_buscar.BorderRadius = 1;
            this.txt_buscar.BorderThickness = 1;
            this.txt_buscar.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_buscar.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_buscar.DefaultFont = new System.Drawing.Font("Segoe UI", 10F);
            this.txt_buscar.DefaultText = "";
            this.txt_buscar.FillColor = System.Drawing.SystemColors.ButtonFace;
            this.txt_buscar.HideSelection = true;
            this.txt_buscar.IconLeft = null;
            this.txt_buscar.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_buscar.IconPadding = 10;
            this.txt_buscar.IconRight = null;
            this.txt_buscar.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_buscar.Lines = new string[0];
            this.txt_buscar.Location = new System.Drawing.Point(53, 12);
            this.txt_buscar.MaxLength = 32767;
            this.txt_buscar.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_buscar.Modified = false;
            this.txt_buscar.Multiline = false;
            this.txt_buscar.Name = "txt_buscar";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_buscar.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_buscar.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_buscar.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.SystemColors.ButtonFace;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_buscar.OnIdleState = stateProperties4;
            this.txt_buscar.Padding = new System.Windows.Forms.Padding(3);
            this.txt_buscar.PasswordChar = '\0';
            this.txt_buscar.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txt_buscar.PlaceholderText = "Buscar...";
            this.txt_buscar.ReadOnly = false;
            this.txt_buscar.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_buscar.SelectedText = "";
            this.txt_buscar.SelectionLength = 0;
            this.txt_buscar.SelectionStart = 0;
            this.txt_buscar.ShortcutsEnabled = true;
            this.txt_buscar.Size = new System.Drawing.Size(248, 37);
            this.txt_buscar.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_buscar.TabIndex = 0;
            this.txt_buscar.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_buscar.TextMarginBottom = 0;
            this.txt_buscar.TextMarginLeft = 3;
            this.txt_buscar.TextMarginTop = 0;
            this.txt_buscar.TextPlaceholder = "Buscar...";
            this.txt_buscar.UseSystemPasswordChar = false;
            this.txt_buscar.WordWrap = true;
            this.txt_buscar.TextChanged += new System.EventHandler(this.txt_buscar_TextChanged);
            this.txt_buscar.KeyUp += new System.Windows.Forms.KeyEventHandler(this.txt_buscar_KeyUp);
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.btn_user_elimiar);
            this.bunifuPanel1.Controls.Add(this.btn_user_limpiar);
            this.bunifuPanel1.Controls.Add(this.dtp_user_date_birth);
            this.bunifuPanel1.Controls.Add(this.lbl_user_date_birth);
            this.bunifuPanel1.Controls.Add(this.txt_user_dni);
            this.bunifuPanel1.Controls.Add(this.txt_user_adress);
            this.bunifuPanel1.Controls.Add(this.txt_user_tel);
            this.bunifuPanel1.Controls.Add(this.btn_user_modificar);
            this.bunifuPanel1.Controls.Add(this.txt_user_nombre);
            this.bunifuPanel1.Controls.Add(this.txt_user_apellido);
            this.bunifuPanel1.Controls.Add(this.txt_user_email);
            this.bunifuPanel1.Controls.Add(this.btn_user_agregar);
            this.bunifuPanel1.Location = new System.Drawing.Point(32, 145);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(741, 204);
            this.bunifuPanel1.TabIndex = 22;
            // 
            // btn_user_elimiar
            // 
            this.btn_user_elimiar.AllowAnimations = true;
            this.btn_user_elimiar.AllowMouseEffects = true;
            this.btn_user_elimiar.AllowToggling = false;
            this.btn_user_elimiar.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btn_user_elimiar.AnimationSpeed = 200;
            this.btn_user_elimiar.AutoGenerateColors = false;
            this.btn_user_elimiar.AutoRoundBorders = false;
            this.btn_user_elimiar.AutoSizeLeftIcon = true;
            this.btn_user_elimiar.AutoSizeRightIcon = true;
            this.btn_user_elimiar.BackColor = System.Drawing.Color.Transparent;
            this.btn_user_elimiar.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btn_user_elimiar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_user_elimiar.BackgroundImage")));
            this.btn_user_elimiar.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.btn_user_elimiar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_elimiar.ButtonText = "Eliminar";
            this.btn_user_elimiar.ButtonTextMarginLeft = 0;
            this.btn_user_elimiar.ColorContrastOnClick = 45;
            this.btn_user_elimiar.ColorContrastOnHover = 45;
            this.btn_user_elimiar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btn_user_elimiar.CustomizableEdges = borderEdges1;
            this.btn_user_elimiar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_user_elimiar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_user_elimiar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_user_elimiar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_user_elimiar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_user_elimiar.Font = new System.Drawing.Font("Segoe UI Emoji", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_user_elimiar.ForeColor = System.Drawing.Color.White;
            this.btn_user_elimiar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_user_elimiar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_user_elimiar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_user_elimiar.IconMarginLeft = 11;
            this.btn_user_elimiar.IconPadding = 10;
            this.btn_user_elimiar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_user_elimiar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_user_elimiar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_user_elimiar.IconSize = 25;
            this.btn_user_elimiar.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btn_user_elimiar.IdleBorderRadius = 1;
            this.btn_user_elimiar.IdleBorderThickness = 1;
            this.btn_user_elimiar.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btn_user_elimiar.IdleIconLeftImage = global::ProyectoTallerII.Properties.Resources.remove_ico__1_;
            this.btn_user_elimiar.IdleIconRightImage = null;
            this.btn_user_elimiar.IndicateFocus = false;
            this.btn_user_elimiar.Location = new System.Drawing.Point(551, 93);
            this.btn_user_elimiar.Name = "btn_user_elimiar";
            this.btn_user_elimiar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_user_elimiar.OnDisabledState.BorderRadius = 1;
            this.btn_user_elimiar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_elimiar.OnDisabledState.BorderThickness = 1;
            this.btn_user_elimiar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_user_elimiar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_user_elimiar.OnDisabledState.IconLeftImage = null;
            this.btn_user_elimiar.OnDisabledState.IconRightImage = null;
            this.btn_user_elimiar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_user_elimiar.onHoverState.BorderRadius = 1;
            this.btn_user_elimiar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_elimiar.onHoverState.BorderThickness = 1;
            this.btn_user_elimiar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_user_elimiar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_user_elimiar.onHoverState.IconLeftImage = null;
            this.btn_user_elimiar.onHoverState.IconRightImage = null;
            this.btn_user_elimiar.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btn_user_elimiar.OnIdleState.BorderRadius = 1;
            this.btn_user_elimiar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_elimiar.OnIdleState.BorderThickness = 1;
            this.btn_user_elimiar.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btn_user_elimiar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_user_elimiar.OnIdleState.IconLeftImage = global::ProyectoTallerII.Properties.Resources.remove_ico__1_;
            this.btn_user_elimiar.OnIdleState.IconRightImage = null;
            this.btn_user_elimiar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_user_elimiar.OnPressedState.BorderRadius = 1;
            this.btn_user_elimiar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_elimiar.OnPressedState.BorderThickness = 1;
            this.btn_user_elimiar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_user_elimiar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_user_elimiar.OnPressedState.IconLeftImage = null;
            this.btn_user_elimiar.OnPressedState.IconRightImage = null;
            this.btn_user_elimiar.Size = new System.Drawing.Size(150, 39);
            this.btn_user_elimiar.TabIndex = 24;
            this.btn_user_elimiar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_user_elimiar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_user_elimiar.TextMarginLeft = 0;
            this.btn_user_elimiar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_user_elimiar.UseDefaultRadiusAndThickness = true;
            this.btn_user_elimiar.Click += new System.EventHandler(this.btn_user_elimiar_Click);
            // 
            // btn_user_limpiar
            // 
            this.btn_user_limpiar.AllowAnimations = true;
            this.btn_user_limpiar.AllowMouseEffects = true;
            this.btn_user_limpiar.AllowToggling = false;
            this.btn_user_limpiar.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btn_user_limpiar.AnimationSpeed = 200;
            this.btn_user_limpiar.AutoGenerateColors = false;
            this.btn_user_limpiar.AutoRoundBorders = false;
            this.btn_user_limpiar.AutoSizeLeftIcon = true;
            this.btn_user_limpiar.AutoSizeRightIcon = true;
            this.btn_user_limpiar.BackColor = System.Drawing.Color.Transparent;
            this.btn_user_limpiar.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btn_user_limpiar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_user_limpiar.BackgroundImage")));
            this.btn_user_limpiar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_limpiar.ButtonText = "Limpiar";
            this.btn_user_limpiar.ButtonTextMarginLeft = 0;
            this.btn_user_limpiar.ColorContrastOnClick = 45;
            this.btn_user_limpiar.ColorContrastOnHover = 45;
            this.btn_user_limpiar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btn_user_limpiar.CustomizableEdges = borderEdges2;
            this.btn_user_limpiar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_user_limpiar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_user_limpiar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_user_limpiar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_user_limpiar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_user_limpiar.Font = new System.Drawing.Font("Segoe UI Emoji", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_user_limpiar.ForeColor = System.Drawing.Color.White;
            this.btn_user_limpiar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_user_limpiar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_user_limpiar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_user_limpiar.IconMarginLeft = 11;
            this.btn_user_limpiar.IconPadding = 10;
            this.btn_user_limpiar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_user_limpiar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_user_limpiar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_user_limpiar.IconSize = 25;
            this.btn_user_limpiar.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btn_user_limpiar.IdleBorderRadius = 1;
            this.btn_user_limpiar.IdleBorderThickness = 1;
            this.btn_user_limpiar.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btn_user_limpiar.IdleIconLeftImage = global::ProyectoTallerII.Properties.Resources.eraser__1_;
            this.btn_user_limpiar.IdleIconRightImage = null;
            this.btn_user_limpiar.IndicateFocus = false;
            this.btn_user_limpiar.Location = new System.Drawing.Point(551, 136);
            this.btn_user_limpiar.Name = "btn_user_limpiar";
            this.btn_user_limpiar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_user_limpiar.OnDisabledState.BorderRadius = 1;
            this.btn_user_limpiar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_limpiar.OnDisabledState.BorderThickness = 1;
            this.btn_user_limpiar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_user_limpiar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_user_limpiar.OnDisabledState.IconLeftImage = null;
            this.btn_user_limpiar.OnDisabledState.IconRightImage = null;
            this.btn_user_limpiar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_user_limpiar.onHoverState.BorderRadius = 1;
            this.btn_user_limpiar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_limpiar.onHoverState.BorderThickness = 1;
            this.btn_user_limpiar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_user_limpiar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_user_limpiar.onHoverState.IconLeftImage = null;
            this.btn_user_limpiar.onHoverState.IconRightImage = null;
            this.btn_user_limpiar.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btn_user_limpiar.OnIdleState.BorderRadius = 1;
            this.btn_user_limpiar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_limpiar.OnIdleState.BorderThickness = 1;
            this.btn_user_limpiar.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btn_user_limpiar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_user_limpiar.OnIdleState.IconLeftImage = global::ProyectoTallerII.Properties.Resources.eraser__1_;
            this.btn_user_limpiar.OnIdleState.IconRightImage = null;
            this.btn_user_limpiar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_user_limpiar.OnPressedState.BorderRadius = 1;
            this.btn_user_limpiar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_limpiar.OnPressedState.BorderThickness = 1;
            this.btn_user_limpiar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_user_limpiar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_user_limpiar.OnPressedState.IconLeftImage = null;
            this.btn_user_limpiar.OnPressedState.IconRightImage = null;
            this.btn_user_limpiar.Size = new System.Drawing.Size(150, 39);
            this.btn_user_limpiar.TabIndex = 23;
            this.btn_user_limpiar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_user_limpiar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_user_limpiar.TextMarginLeft = 0;
            this.btn_user_limpiar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_user_limpiar.UseDefaultRadiusAndThickness = true;
            this.btn_user_limpiar.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // dtp_user_date_birth
            // 
            this.dtp_user_date_birth.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.dtp_user_date_birth.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.dtp_user_date_birth.BorderRadius = 1;
            this.dtp_user_date_birth.CalendarFont = new System.Drawing.Font("Segoe UI Emoji", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dtp_user_date_birth.Color = System.Drawing.Color.Silver;
            this.dtp_user_date_birth.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.dtp_user_date_birth.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dtp_user_date_birth.DisabledColor = System.Drawing.Color.Gray;
            this.dtp_user_date_birth.DisplayWeekNumbers = false;
            this.dtp_user_date_birth.DPHeight = 0;
            this.dtp_user_date_birth.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.dtp_user_date_birth.FillDatePicker = false;
            this.dtp_user_date_birth.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.dtp_user_date_birth.ForeColor = System.Drawing.Color.Black;
            this.dtp_user_date_birth.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dtp_user_date_birth.Icon = ((System.Drawing.Image)(resources.GetObject("dtp_user_date_birth.Icon")));
            this.dtp_user_date_birth.IconColor = System.Drawing.Color.Gray;
            this.dtp_user_date_birth.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dtp_user_date_birth.LeftTextMargin = 5;
            this.dtp_user_date_birth.Location = new System.Drawing.Point(385, 91);
            this.dtp_user_date_birth.MinimumSize = new System.Drawing.Size(4, 32);
            this.dtp_user_date_birth.Name = "dtp_user_date_birth";
            this.dtp_user_date_birth.Size = new System.Drawing.Size(97, 32);
            this.dtp_user_date_birth.TabIndex = 7;
            // 
            // lbl_user_date_birth
            // 
            this.lbl_user_date_birth.AllowParentOverrides = false;
            this.lbl_user_date_birth.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.lbl_user_date_birth.AutoEllipsis = false;
            this.lbl_user_date_birth.Cursor = System.Windows.Forms.Cursors.Default;
            this.lbl_user_date_birth.CursorType = System.Windows.Forms.Cursors.Default;
            this.lbl_user_date_birth.Font = new System.Drawing.Font("Segoe UI Emoji", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbl_user_date_birth.Location = new System.Drawing.Point(284, 91);
            this.lbl_user_date_birth.Name = "lbl_user_date_birth";
            this.lbl_user_date_birth.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lbl_user_date_birth.Size = new System.Drawing.Size(95, 21);
            this.lbl_user_date_birth.TabIndex = 21;
            this.lbl_user_date_birth.Text = "Fecha de Nac.";
            this.lbl_user_date_birth.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lbl_user_date_birth.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txt_user_dni
            // 
            this.txt_user_dni.AcceptsReturn = false;
            this.txt_user_dni.AcceptsTab = false;
            this.txt_user_dni.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txt_user_dni.AnimationSpeed = 200;
            this.txt_user_dni.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_user_dni.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_user_dni.BackColor = System.Drawing.Color.Transparent;
            this.txt_user_dni.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_user_dni.BackgroundImage")));
            this.txt_user_dni.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_user_dni.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_user_dni.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_user_dni.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_user_dni.BorderRadius = 1;
            this.txt_user_dni.BorderThickness = 1;
            this.txt_user_dni.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_user_dni.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_dni.DefaultFont = new System.Drawing.Font("Segoe UI", 10F);
            this.txt_user_dni.DefaultText = "";
            this.txt_user_dni.FillColor = System.Drawing.SystemColors.ButtonFace;
            this.txt_user_dni.HideSelection = true;
            this.txt_user_dni.IconLeft = null;
            this.txt_user_dni.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_dni.IconPadding = 10;
            this.txt_user_dni.IconRight = null;
            this.txt_user_dni.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_dni.Lines = new string[0];
            this.txt_user_dni.Location = new System.Drawing.Point(50, 91);
            this.txt_user_dni.MaxLength = 8;
            this.txt_user_dni.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_user_dni.Modified = false;
            this.txt_user_dni.Multiline = false;
            this.txt_user_dni.Name = "txt_user_dni";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_dni.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_user_dni.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_dni.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.SystemColors.ButtonFace;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_dni.OnIdleState = stateProperties8;
            this.txt_user_dni.Padding = new System.Windows.Forms.Padding(3);
            this.txt_user_dni.PasswordChar = '\0';
            this.txt_user_dni.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txt_user_dni.PlaceholderText = "DNI";
            this.txt_user_dni.ReadOnly = false;
            this.txt_user_dni.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_user_dni.SelectedText = "";
            this.txt_user_dni.SelectionLength = 0;
            this.txt_user_dni.SelectionStart = 0;
            this.txt_user_dni.ShortcutsEnabled = true;
            this.txt_user_dni.Size = new System.Drawing.Size(198, 38);
            this.txt_user_dni.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_user_dni.TabIndex = 3;
            this.txt_user_dni.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_user_dni.TextMarginBottom = 0;
            this.txt_user_dni.TextMarginLeft = 3;
            this.txt_user_dni.TextMarginTop = 0;
            this.txt_user_dni.TextPlaceholder = "DNI";
            this.txt_user_dni.UseSystemPasswordChar = false;
            this.txt_user_dni.WordWrap = true;
            this.txt_user_dni.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_user_dni_KeyPress);
            // 
            // txt_user_adress
            // 
            this.txt_user_adress.AcceptsReturn = false;
            this.txt_user_adress.AcceptsTab = false;
            this.txt_user_adress.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txt_user_adress.AnimationSpeed = 200;
            this.txt_user_adress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_user_adress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_user_adress.BackColor = System.Drawing.Color.Transparent;
            this.txt_user_adress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_user_adress.BackgroundImage")));
            this.txt_user_adress.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_user_adress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_user_adress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_user_adress.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_user_adress.BorderRadius = 1;
            this.txt_user_adress.BorderThickness = 1;
            this.txt_user_adress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_user_adress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_adress.DefaultFont = new System.Drawing.Font("Segoe UI", 10F);
            this.txt_user_adress.DefaultText = "";
            this.txt_user_adress.FillColor = System.Drawing.SystemColors.ButtonFace;
            this.txt_user_adress.HideSelection = true;
            this.txt_user_adress.IconLeft = null;
            this.txt_user_adress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_adress.IconPadding = 10;
            this.txt_user_adress.IconRight = null;
            this.txt_user_adress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_adress.Lines = new string[0];
            this.txt_user_adress.Location = new System.Drawing.Point(284, 47);
            this.txt_user_adress.MaxLength = 32767;
            this.txt_user_adress.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_user_adress.Modified = false;
            this.txt_user_adress.Multiline = false;
            this.txt_user_adress.Name = "txt_user_adress";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_adress.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_user_adress.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_adress.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.SystemColors.ButtonFace;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_adress.OnIdleState = stateProperties12;
            this.txt_user_adress.Padding = new System.Windows.Forms.Padding(3);
            this.txt_user_adress.PasswordChar = '\0';
            this.txt_user_adress.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txt_user_adress.PlaceholderText = "Dirección";
            this.txt_user_adress.ReadOnly = false;
            this.txt_user_adress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_user_adress.SelectedText = "";
            this.txt_user_adress.SelectionLength = 0;
            this.txt_user_adress.SelectionStart = 0;
            this.txt_user_adress.ShortcutsEnabled = true;
            this.txt_user_adress.Size = new System.Drawing.Size(198, 38);
            this.txt_user_adress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_user_adress.TabIndex = 6;
            this.txt_user_adress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_user_adress.TextMarginBottom = 0;
            this.txt_user_adress.TextMarginLeft = 3;
            this.txt_user_adress.TextMarginTop = 0;
            this.txt_user_adress.TextPlaceholder = "Dirección";
            this.txt_user_adress.UseSystemPasswordChar = false;
            this.txt_user_adress.WordWrap = true;
            // 
            // txt_user_tel
            // 
            this.txt_user_tel.AcceptsReturn = false;
            this.txt_user_tel.AcceptsTab = false;
            this.txt_user_tel.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txt_user_tel.AnimationSpeed = 200;
            this.txt_user_tel.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_user_tel.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_user_tel.BackColor = System.Drawing.Color.Transparent;
            this.txt_user_tel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_user_tel.BackgroundImage")));
            this.txt_user_tel.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_user_tel.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_user_tel.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_user_tel.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_user_tel.BorderRadius = 1;
            this.txt_user_tel.BorderThickness = 1;
            this.txt_user_tel.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_user_tel.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_tel.DefaultFont = new System.Drawing.Font("Segoe UI", 10F);
            this.txt_user_tel.DefaultText = "";
            this.txt_user_tel.FillColor = System.Drawing.SystemColors.ButtonFace;
            this.txt_user_tel.HideSelection = true;
            this.txt_user_tel.IconLeft = null;
            this.txt_user_tel.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_tel.IconPadding = 10;
            this.txt_user_tel.IconRight = null;
            this.txt_user_tel.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_tel.Lines = new string[0];
            this.txt_user_tel.Location = new System.Drawing.Point(284, 3);
            this.txt_user_tel.MaxLength = 32767;
            this.txt_user_tel.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_user_tel.Modified = false;
            this.txt_user_tel.Multiline = false;
            this.txt_user_tel.Name = "txt_user_tel";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_tel.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_user_tel.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_tel.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.SystemColors.ButtonFace;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_tel.OnIdleState = stateProperties16;
            this.txt_user_tel.Padding = new System.Windows.Forms.Padding(3);
            this.txt_user_tel.PasswordChar = '\0';
            this.txt_user_tel.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txt_user_tel.PlaceholderText = "Teléfono";
            this.txt_user_tel.ReadOnly = false;
            this.txt_user_tel.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_user_tel.SelectedText = "";
            this.txt_user_tel.SelectionLength = 0;
            this.txt_user_tel.SelectionStart = 0;
            this.txt_user_tel.ShortcutsEnabled = true;
            this.txt_user_tel.Size = new System.Drawing.Size(198, 38);
            this.txt_user_tel.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_user_tel.TabIndex = 5;
            this.txt_user_tel.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_user_tel.TextMarginBottom = 0;
            this.txt_user_tel.TextMarginLeft = 3;
            this.txt_user_tel.TextMarginTop = 0;
            this.txt_user_tel.TextPlaceholder = "Teléfono";
            this.txt_user_tel.UseSystemPasswordChar = false;
            this.txt_user_tel.WordWrap = true;
            this.txt_user_tel.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_user_tel_KeyPress);
            // 
            // btn_user_modificar
            // 
            this.btn_user_modificar.AllowAnimations = true;
            this.btn_user_modificar.AllowMouseEffects = true;
            this.btn_user_modificar.AllowToggling = false;
            this.btn_user_modificar.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btn_user_modificar.AnimationSpeed = 200;
            this.btn_user_modificar.AutoGenerateColors = false;
            this.btn_user_modificar.AutoRoundBorders = false;
            this.btn_user_modificar.AutoSizeLeftIcon = true;
            this.btn_user_modificar.AutoSizeRightIcon = true;
            this.btn_user_modificar.BackColor = System.Drawing.Color.Transparent;
            this.btn_user_modificar.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btn_user_modificar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_user_modificar.BackgroundImage")));
            this.btn_user_modificar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_modificar.ButtonText = "Modificar";
            this.btn_user_modificar.ButtonTextMarginLeft = 0;
            this.btn_user_modificar.ColorContrastOnClick = 45;
            this.btn_user_modificar.ColorContrastOnHover = 45;
            this.btn_user_modificar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btn_user_modificar.CustomizableEdges = borderEdges3;
            this.btn_user_modificar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_user_modificar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_user_modificar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_user_modificar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_user_modificar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_user_modificar.Font = new System.Drawing.Font("Segoe UI Emoji", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_user_modificar.ForeColor = System.Drawing.Color.White;
            this.btn_user_modificar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_user_modificar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_user_modificar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_user_modificar.IconMarginLeft = 11;
            this.btn_user_modificar.IconPadding = 10;
            this.btn_user_modificar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_user_modificar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_user_modificar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_user_modificar.IconSize = 25;
            this.btn_user_modificar.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btn_user_modificar.IdleBorderRadius = 1;
            this.btn_user_modificar.IdleBorderThickness = 1;
            this.btn_user_modificar.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btn_user_modificar.IdleIconLeftImage = global::ProyectoTallerII.Properties.Resources.ui_settings__1_;
            this.btn_user_modificar.IdleIconRightImage = null;
            this.btn_user_modificar.IndicateFocus = false;
            this.btn_user_modificar.Location = new System.Drawing.Point(551, 48);
            this.btn_user_modificar.Name = "btn_user_modificar";
            this.btn_user_modificar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_user_modificar.OnDisabledState.BorderRadius = 1;
            this.btn_user_modificar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_modificar.OnDisabledState.BorderThickness = 1;
            this.btn_user_modificar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_user_modificar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_user_modificar.OnDisabledState.IconLeftImage = null;
            this.btn_user_modificar.OnDisabledState.IconRightImage = null;
            this.btn_user_modificar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_user_modificar.onHoverState.BorderRadius = 1;
            this.btn_user_modificar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_modificar.onHoverState.BorderThickness = 1;
            this.btn_user_modificar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_user_modificar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_user_modificar.onHoverState.IconLeftImage = null;
            this.btn_user_modificar.onHoverState.IconRightImage = null;
            this.btn_user_modificar.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btn_user_modificar.OnIdleState.BorderRadius = 1;
            this.btn_user_modificar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_modificar.OnIdleState.BorderThickness = 1;
            this.btn_user_modificar.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btn_user_modificar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_user_modificar.OnIdleState.IconLeftImage = global::ProyectoTallerII.Properties.Resources.ui_settings__1_;
            this.btn_user_modificar.OnIdleState.IconRightImage = null;
            this.btn_user_modificar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_user_modificar.OnPressedState.BorderRadius = 1;
            this.btn_user_modificar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_modificar.OnPressedState.BorderThickness = 1;
            this.btn_user_modificar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_user_modificar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_user_modificar.OnPressedState.IconLeftImage = null;
            this.btn_user_modificar.OnPressedState.IconRightImage = null;
            this.btn_user_modificar.Size = new System.Drawing.Size(150, 39);
            this.btn_user_modificar.TabIndex = 14;
            this.btn_user_modificar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_user_modificar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_user_modificar.TextMarginLeft = 0;
            this.btn_user_modificar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_user_modificar.UseDefaultRadiusAndThickness = true;
            this.btn_user_modificar.Click += new System.EventHandler(this.btn_user_modificar_Click);
            // 
            // txt_user_nombre
            // 
            this.txt_user_nombre.AcceptsReturn = false;
            this.txt_user_nombre.AcceptsTab = false;
            this.txt_user_nombre.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txt_user_nombre.AnimationSpeed = 200;
            this.txt_user_nombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_user_nombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_user_nombre.BackColor = System.Drawing.Color.Transparent;
            this.txt_user_nombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_user_nombre.BackgroundImage")));
            this.txt_user_nombre.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_user_nombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_user_nombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_user_nombre.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_user_nombre.BorderRadius = 1;
            this.txt_user_nombre.BorderThickness = 1;
            this.txt_user_nombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_user_nombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_nombre.DefaultFont = new System.Drawing.Font("Segoe UI", 10F);
            this.txt_user_nombre.DefaultText = "";
            this.txt_user_nombre.FillColor = System.Drawing.SystemColors.ButtonFace;
            this.txt_user_nombre.HideSelection = true;
            this.txt_user_nombre.IconLeft = null;
            this.txt_user_nombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_nombre.IconPadding = 10;
            this.txt_user_nombre.IconRight = null;
            this.txt_user_nombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_nombre.Lines = new string[0];
            this.txt_user_nombre.Location = new System.Drawing.Point(50, 3);
            this.txt_user_nombre.MaxLength = 32767;
            this.txt_user_nombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_user_nombre.Modified = false;
            this.txt_user_nombre.Multiline = false;
            this.txt_user_nombre.Name = "txt_user_nombre";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_nombre.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_user_nombre.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_nombre.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.SystemColors.ButtonFace;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_nombre.OnIdleState = stateProperties20;
            this.txt_user_nombre.Padding = new System.Windows.Forms.Padding(3);
            this.txt_user_nombre.PasswordChar = '\0';
            this.txt_user_nombre.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txt_user_nombre.PlaceholderText = "Nombre";
            this.txt_user_nombre.ReadOnly = false;
            this.txt_user_nombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_user_nombre.SelectedText = "";
            this.txt_user_nombre.SelectionLength = 0;
            this.txt_user_nombre.SelectionStart = 0;
            this.txt_user_nombre.ShortcutsEnabled = true;
            this.txt_user_nombre.Size = new System.Drawing.Size(198, 38);
            this.txt_user_nombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_user_nombre.TabIndex = 1;
            this.txt_user_nombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_user_nombre.TextMarginBottom = 0;
            this.txt_user_nombre.TextMarginLeft = 3;
            this.txt_user_nombre.TextMarginTop = 0;
            this.txt_user_nombre.TextPlaceholder = "Nombre";
            this.txt_user_nombre.UseSystemPasswordChar = false;
            this.txt_user_nombre.WordWrap = true;
            this.txt_user_nombre.TextChange += new System.EventHandler(this.txt_user_nombre_TextChange);
            this.txt_user_nombre.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_user_nombre_KeyPress);
            // 
            // txt_user_apellido
            // 
            this.txt_user_apellido.AcceptsReturn = false;
            this.txt_user_apellido.AcceptsTab = false;
            this.txt_user_apellido.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txt_user_apellido.AnimationSpeed = 200;
            this.txt_user_apellido.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_user_apellido.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_user_apellido.BackColor = System.Drawing.Color.Transparent;
            this.txt_user_apellido.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_user_apellido.BackgroundImage")));
            this.txt_user_apellido.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_user_apellido.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_user_apellido.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_user_apellido.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_user_apellido.BorderRadius = 1;
            this.txt_user_apellido.BorderThickness = 1;
            this.txt_user_apellido.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_user_apellido.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_apellido.DefaultFont = new System.Drawing.Font("Segoe UI", 10F);
            this.txt_user_apellido.DefaultText = "";
            this.txt_user_apellido.FillColor = System.Drawing.SystemColors.ButtonFace;
            this.txt_user_apellido.HideSelection = true;
            this.txt_user_apellido.IconLeft = null;
            this.txt_user_apellido.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_apellido.IconPadding = 10;
            this.txt_user_apellido.IconRight = null;
            this.txt_user_apellido.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_apellido.Lines = new string[0];
            this.txt_user_apellido.Location = new System.Drawing.Point(50, 47);
            this.txt_user_apellido.MaxLength = 32767;
            this.txt_user_apellido.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_user_apellido.Modified = false;
            this.txt_user_apellido.Multiline = false;
            this.txt_user_apellido.Name = "txt_user_apellido";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_apellido.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_user_apellido.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_apellido.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.SystemColors.ButtonFace;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_apellido.OnIdleState = stateProperties24;
            this.txt_user_apellido.Padding = new System.Windows.Forms.Padding(3);
            this.txt_user_apellido.PasswordChar = '\0';
            this.txt_user_apellido.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txt_user_apellido.PlaceholderText = "Apellido";
            this.txt_user_apellido.ReadOnly = false;
            this.txt_user_apellido.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_user_apellido.SelectedText = "";
            this.txt_user_apellido.SelectionLength = 0;
            this.txt_user_apellido.SelectionStart = 0;
            this.txt_user_apellido.ShortcutsEnabled = true;
            this.txt_user_apellido.Size = new System.Drawing.Size(198, 38);
            this.txt_user_apellido.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_user_apellido.TabIndex = 2;
            this.txt_user_apellido.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_user_apellido.TextMarginBottom = 0;
            this.txt_user_apellido.TextMarginLeft = 3;
            this.txt_user_apellido.TextMarginTop = 0;
            this.txt_user_apellido.TextPlaceholder = "Apellido";
            this.txt_user_apellido.UseSystemPasswordChar = false;
            this.txt_user_apellido.WordWrap = true;
            this.txt_user_apellido.TextChanged += new System.EventHandler(this.txt_user_apellido_TextChanged);
            this.txt_user_apellido.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_user_apellido_KeyPress);
            // 
            // txt_user_email
            // 
            this.txt_user_email.AcceptsReturn = false;
            this.txt_user_email.AcceptsTab = false;
            this.txt_user_email.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txt_user_email.AnimationSpeed = 200;
            this.txt_user_email.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_user_email.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_user_email.BackColor = System.Drawing.Color.Transparent;
            this.txt_user_email.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_user_email.BackgroundImage")));
            this.txt_user_email.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_user_email.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_user_email.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_user_email.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_user_email.BorderRadius = 1;
            this.txt_user_email.BorderThickness = 1;
            this.txt_user_email.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_user_email.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_email.DefaultFont = new System.Drawing.Font("Segoe UI", 10F);
            this.txt_user_email.DefaultText = "";
            this.txt_user_email.FillColor = System.Drawing.SystemColors.ButtonFace;
            this.txt_user_email.HideSelection = true;
            this.txt_user_email.IconLeft = null;
            this.txt_user_email.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_email.IconPadding = 10;
            this.txt_user_email.IconRight = null;
            this.txt_user_email.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_user_email.Lines = new string[0];
            this.txt_user_email.Location = new System.Drawing.Point(50, 135);
            this.txt_user_email.MaxLength = 32767;
            this.txt_user_email.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_user_email.Modified = false;
            this.txt_user_email.Multiline = false;
            this.txt_user_email.Name = "txt_user_email";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_email.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_user_email.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_email.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.SystemColors.ButtonFace;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_user_email.OnIdleState = stateProperties28;
            this.txt_user_email.Padding = new System.Windows.Forms.Padding(3);
            this.txt_user_email.PasswordChar = '\0';
            this.txt_user_email.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txt_user_email.PlaceholderText = "E-mail";
            this.txt_user_email.ReadOnly = false;
            this.txt_user_email.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_user_email.SelectedText = "";
            this.txt_user_email.SelectionLength = 0;
            this.txt_user_email.SelectionStart = 0;
            this.txt_user_email.ShortcutsEnabled = true;
            this.txt_user_email.Size = new System.Drawing.Size(198, 38);
            this.txt_user_email.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_user_email.TabIndex = 4;
            this.txt_user_email.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_user_email.TextMarginBottom = 0;
            this.txt_user_email.TextMarginLeft = 3;
            this.txt_user_email.TextMarginTop = 0;
            this.txt_user_email.TextPlaceholder = "E-mail";
            this.txt_user_email.UseSystemPasswordChar = false;
            this.txt_user_email.WordWrap = true;
            this.txt_user_email.TextChanged += new System.EventHandler(this.txt_user_email_TextChanged);
            this.txt_user_email.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_user_email_KeyPress);
            // 
            // btn_user_agregar
            // 
            this.btn_user_agregar.AllowAnimations = true;
            this.btn_user_agregar.AllowMouseEffects = true;
            this.btn_user_agregar.AllowToggling = false;
            this.btn_user_agregar.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btn_user_agregar.AnimationSpeed = 200;
            this.btn_user_agregar.AutoGenerateColors = false;
            this.btn_user_agregar.AutoRoundBorders = false;
            this.btn_user_agregar.AutoSizeLeftIcon = true;
            this.btn_user_agregar.AutoSizeRightIcon = true;
            this.btn_user_agregar.BackColor = System.Drawing.Color.Transparent;
            this.btn_user_agregar.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btn_user_agregar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_user_agregar.BackgroundImage")));
            this.btn_user_agregar.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.btn_user_agregar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_agregar.ButtonText = "Guardar";
            this.btn_user_agregar.ButtonTextMarginLeft = 0;
            this.btn_user_agregar.ColorContrastOnClick = 45;
            this.btn_user_agregar.ColorContrastOnHover = 45;
            this.btn_user_agregar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btn_user_agregar.CustomizableEdges = borderEdges4;
            this.btn_user_agregar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_user_agregar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_user_agregar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_user_agregar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_user_agregar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_user_agregar.Font = new System.Drawing.Font("Segoe UI Emoji", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_user_agregar.ForeColor = System.Drawing.Color.White;
            this.btn_user_agregar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_user_agregar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_user_agregar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_user_agregar.IconMarginLeft = 11;
            this.btn_user_agregar.IconPadding = 10;
            this.btn_user_agregar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_user_agregar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_user_agregar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_user_agregar.IconSize = 25;
            this.btn_user_agregar.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btn_user_agregar.IdleBorderRadius = 1;
            this.btn_user_agregar.IdleBorderThickness = 1;
            this.btn_user_agregar.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btn_user_agregar.IdleIconLeftImage = global::ProyectoTallerII.Properties.Resources.save__1_;
            this.btn_user_agregar.IdleIconRightImage = null;
            this.btn_user_agregar.IndicateFocus = false;
            this.btn_user_agregar.Location = new System.Drawing.Point(551, 3);
            this.btn_user_agregar.Name = "btn_user_agregar";
            this.btn_user_agregar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_user_agregar.OnDisabledState.BorderRadius = 1;
            this.btn_user_agregar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_agregar.OnDisabledState.BorderThickness = 1;
            this.btn_user_agregar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_user_agregar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_user_agregar.OnDisabledState.IconLeftImage = null;
            this.btn_user_agregar.OnDisabledState.IconRightImage = null;
            this.btn_user_agregar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_user_agregar.onHoverState.BorderRadius = 1;
            this.btn_user_agregar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_agregar.onHoverState.BorderThickness = 1;
            this.btn_user_agregar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_user_agregar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_user_agregar.onHoverState.IconLeftImage = null;
            this.btn_user_agregar.onHoverState.IconRightImage = null;
            this.btn_user_agregar.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btn_user_agregar.OnIdleState.BorderRadius = 1;
            this.btn_user_agregar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_agregar.OnIdleState.BorderThickness = 1;
            this.btn_user_agregar.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btn_user_agregar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_user_agregar.OnIdleState.IconLeftImage = global::ProyectoTallerII.Properties.Resources.save__1_;
            this.btn_user_agregar.OnIdleState.IconRightImage = null;
            this.btn_user_agregar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_user_agregar.OnPressedState.BorderRadius = 1;
            this.btn_user_agregar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_agregar.OnPressedState.BorderThickness = 1;
            this.btn_user_agregar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_user_agregar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_user_agregar.OnPressedState.IconLeftImage = null;
            this.btn_user_agregar.OnPressedState.IconRightImage = null;
            this.btn_user_agregar.Size = new System.Drawing.Size(150, 39);
            this.btn_user_agregar.TabIndex = 11;
            this.btn_user_agregar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_user_agregar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_user_agregar.TextMarginLeft = 0;
            this.btn_user_agregar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_user_agregar.UseDefaultRadiusAndThickness = true;
            this.btn_user_agregar.Click += new System.EventHandler(this.btn_user_agregar_Click);
            // 
            // dataG_usuarios
            // 
            this.dataG_usuarios.AllowUserToAddRows = false;
            this.dataG_usuarios.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.dataG_usuarios.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.AllCells;
            this.dataG_usuarios.AutoSizeRowsMode = System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
            this.dataG_usuarios.BackgroundColor = System.Drawing.Color.DarkSlateBlue;
            this.dataG_usuarios.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dataG_usuarios.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dataG_usuarios.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle1.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.Blue;
            dataGridViewCellStyle1.Font = new System.Drawing.Font("Segoe UI Emoji", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle1.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle1.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle1.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dataG_usuarios.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle1;
            this.dataG_usuarios.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dataG_usuarios.EnableHeadersVisualStyles = false;
            this.dataG_usuarios.GridColor = System.Drawing.Color.GreenYellow;
            this.dataG_usuarios.Location = new System.Drawing.Point(32, 326);
            this.dataG_usuarios.Name = "dataG_usuarios";
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dataG_usuarios.RowHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dataG_usuarios.RowHeadersVisible = false;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.DarkSlateBlue;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Emoji", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.DeepSkyBlue;
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Yellow;
            this.dataG_usuarios.RowsDefaultCellStyle = dataGridViewCellStyle3;
            this.dataG_usuarios.Size = new System.Drawing.Size(741, 203);
            this.dataG_usuarios.TabIndex = 23;
            this.dataG_usuarios.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dataG_usuarios_CellClick);
            // 
            // AdminCliente
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(802, 527);
            this.Controls.Add(this.dataG_usuarios);
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.pnl_buscador);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "AdminCliente";
            this.Text = "Form_vendedor_clientes";
            this.Load += new System.EventHandler(this.Form_vendedor_clientes_Load);
            this.pnl_buscador.ResumeLayout(false);
            this.pnl_buscador.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.lbl_pbuckup)).EndInit();
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataG_usuarios)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel pnl_buscador;
        private System.Windows.Forms.Button button1;
        private Bunifu.UI.WinForms.BunifuPictureBox lbl_pbuckup;
        private Bunifu.UI.WinForms.BunifuLabel lbl_username;
        private Bunifu.UI.WinForms.BunifuLabel lbl_user_title;
        private Bunifu.UI.WinForms.BunifuTextBox txt_buscar;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_user_limpiar;
        private Bunifu.UI.WinForms.BunifuDatePicker dtp_user_date_birth;
        private Bunifu.UI.WinForms.BunifuLabel lbl_user_date_birth;
        private Bunifu.UI.WinForms.BunifuTextBox txt_user_dni;
        private Bunifu.UI.WinForms.BunifuTextBox txt_user_adress;
        private Bunifu.UI.WinForms.BunifuTextBox txt_user_tel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_user_modificar;
        private Bunifu.UI.WinForms.BunifuTextBox txt_user_nombre;
        private Bunifu.UI.WinForms.BunifuTextBox txt_user_apellido;
        private Bunifu.UI.WinForms.BunifuTextBox txt_user_email;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_user_agregar;
        private System.Windows.Forms.DataGridView dataG_usuarios;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_user_elimiar;
    }
}