
namespace ProyectoTallerII
{
    partial class Form_stock
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form_stock));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            this.pnl_buscador = new System.Windows.Forms.Panel();
            this.button1 = new System.Windows.Forms.Button();
            this.lbl_stock_title = new Bunifu.UI.WinForms.BunifuLabel();
            this.txt_buscar = new Bunifu.UI.WinForms.BunifuTextBox();
            this.panel_stock = new Bunifu.UI.WinForms.BunifuPanel();
            this.btn_user_elimiar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txt_stock = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lbl_producto_stock = new Bunifu.UI.WinForms.BunifuLabel();
            this.drd_productos_categoria = new Bunifu.UI.WinForms.BunifuDropdown();
            this.btn_stock_modificar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_stock_limpiar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txt_producto_cod = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_producto_nombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_producto_costo = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btn_stock_agregar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txt_producto_venta = new Bunifu.UI.WinForms.BunifuTextBox();
            this.dtg_stock = new System.Windows.Forms.DataGridView();
            this.pnl_buscador.SuspendLayout();
            this.panel_stock.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dtg_stock)).BeginInit();
            this.SuspendLayout();
            // 
            // pnl_buscador
            // 
            this.pnl_buscador.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.pnl_buscador.Controls.Add(this.button1);
            this.pnl_buscador.Controls.Add(this.lbl_stock_title);
            this.pnl_buscador.Controls.Add(this.txt_buscar);
            this.pnl_buscador.Location = new System.Drawing.Point(33, 57);
            this.pnl_buscador.Name = "pnl_buscador";
            this.pnl_buscador.Size = new System.Drawing.Size(741, 63);
            this.pnl_buscador.TabIndex = 21;
            // 
            // button1
            // 
            this.button1.FlatAppearance.BorderSize = 0;
            this.button1.FlatAppearance.MouseOverBackColor = System.Drawing.Color.BlueViolet;
            this.button1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.button1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12.25F);
            this.button1.ForeColor = System.Drawing.Color.White;
            this.button1.Image = global::ProyectoTallerII.Properties.Resources.search_1__2_;
            this.button1.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.button1.Location = new System.Drawing.Point(6, 12);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(43, 37);
            this.button1.TabIndex = 8;
            this.button1.UseVisualStyleBackColor = true;
            // 
            // lbl_stock_title
            // 
            this.lbl_stock_title.AllowParentOverrides = false;
            this.lbl_stock_title.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.lbl_stock_title.AutoEllipsis = false;
            this.lbl_stock_title.Cursor = System.Windows.Forms.Cursors.Default;
            this.lbl_stock_title.CursorType = System.Windows.Forms.Cursors.Default;
            this.lbl_stock_title.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.lbl_stock_title.Location = new System.Drawing.Point(379, 11);
            this.lbl_stock_title.Name = "lbl_stock_title";
            this.lbl_stock_title.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lbl_stock_title.Size = new System.Drawing.Size(92, 21);
            this.lbl_stock_title.TabIndex = 9;
            this.lbl_stock_title.Text = "PRODUCTOS";
            this.lbl_stock_title.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lbl_stock_title.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txt_buscar
            // 
            this.txt_buscar.AcceptsReturn = false;
            this.txt_buscar.AcceptsTab = false;
            this.txt_buscar.AnimationSpeed = 200;
            this.txt_buscar.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_buscar.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_buscar.BackColor = System.Drawing.Color.Transparent;
            this.txt_buscar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_buscar.BackgroundImage")));
            this.txt_buscar.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_buscar.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_buscar.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_buscar.BorderColorIdle = System.Drawing.Color.Magenta;
            this.txt_buscar.BorderRadius = 20;
            this.txt_buscar.BorderThickness = 2;
            this.txt_buscar.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_buscar.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_buscar.DefaultFont = new System.Drawing.Font("Segoe UI", 10F);
            this.txt_buscar.DefaultText = "";
            this.txt_buscar.FillColor = System.Drawing.SystemColors.ButtonFace;
            this.txt_buscar.HideSelection = true;
            this.txt_buscar.IconLeft = null;
            this.txt_buscar.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_buscar.IconPadding = 10;
            this.txt_buscar.IconRight = null;
            this.txt_buscar.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_buscar.Lines = new string[0];
            this.txt_buscar.Location = new System.Drawing.Point(53, 12);
            this.txt_buscar.MaxLength = 32767;
            this.txt_buscar.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_buscar.Modified = false;
            this.txt_buscar.Multiline = false;
            this.txt_buscar.Name = "txt_buscar";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_buscar.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_buscar.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_buscar.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Magenta;
            stateProperties28.FillColor = System.Drawing.SystemColors.ButtonFace;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_buscar.OnIdleState = stateProperties28;
            this.txt_buscar.Padding = new System.Windows.Forms.Padding(3);
            this.txt_buscar.PasswordChar = '\0';
            this.txt_buscar.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txt_buscar.PlaceholderText = "Buscar...";
            this.txt_buscar.ReadOnly = false;
            this.txt_buscar.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_buscar.SelectedText = "";
            this.txt_buscar.SelectionLength = 0;
            this.txt_buscar.SelectionStart = 0;
            this.txt_buscar.ShortcutsEnabled = true;
            this.txt_buscar.Size = new System.Drawing.Size(248, 37);
            this.txt_buscar.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_buscar.TabIndex = 0;
            this.txt_buscar.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_buscar.TextMarginBottom = 0;
            this.txt_buscar.TextMarginLeft = 3;
            this.txt_buscar.TextMarginTop = 0;
            this.txt_buscar.TextPlaceholder = "Buscar...";
            this.txt_buscar.UseSystemPasswordChar = false;
            this.txt_buscar.WordWrap = true;
            this.txt_buscar.KeyUp += new System.Windows.Forms.KeyEventHandler(this.txt_buscar_KeyUp);
            // 
            // panel_stock
            // 
            this.panel_stock.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.panel_stock.BackgroundColor = System.Drawing.Color.Transparent;
            this.panel_stock.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("panel_stock.BackgroundImage")));
            this.panel_stock.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.panel_stock.BorderColor = System.Drawing.Color.Transparent;
            this.panel_stock.BorderRadius = 3;
            this.panel_stock.BorderThickness = 1;
            this.panel_stock.Controls.Add(this.btn_user_elimiar);
            this.panel_stock.Controls.Add(this.txt_stock);
            this.panel_stock.Controls.Add(this.lbl_producto_stock);
            this.panel_stock.Controls.Add(this.drd_productos_categoria);
            this.panel_stock.Controls.Add(this.btn_stock_modificar);
            this.panel_stock.Controls.Add(this.btn_stock_limpiar);
            this.panel_stock.Controls.Add(this.txt_producto_cod);
            this.panel_stock.Controls.Add(this.txt_producto_nombre);
            this.panel_stock.Controls.Add(this.txt_producto_costo);
            this.panel_stock.Controls.Add(this.btn_stock_agregar);
            this.panel_stock.Controls.Add(this.txt_producto_venta);
            this.panel_stock.Location = new System.Drawing.Point(39, 126);
            this.panel_stock.Name = "panel_stock";
            this.panel_stock.ShowBorders = true;
            this.panel_stock.Size = new System.Drawing.Size(715, 197);
            this.panel_stock.TabIndex = 22;
            // 
            // btn_user_elimiar
            // 
            this.btn_user_elimiar.AllowAnimations = true;
            this.btn_user_elimiar.AllowMouseEffects = true;
            this.btn_user_elimiar.AllowToggling = false;
            this.btn_user_elimiar.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btn_user_elimiar.AnimationSpeed = 200;
            this.btn_user_elimiar.AutoGenerateColors = false;
            this.btn_user_elimiar.AutoRoundBorders = false;
            this.btn_user_elimiar.AutoSizeLeftIcon = true;
            this.btn_user_elimiar.AutoSizeRightIcon = true;
            this.btn_user_elimiar.BackColor = System.Drawing.Color.Transparent;
            this.btn_user_elimiar.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btn_user_elimiar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_user_elimiar.BackgroundImage")));
            this.btn_user_elimiar.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.btn_user_elimiar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_elimiar.ButtonText = "Eliminar";
            this.btn_user_elimiar.ButtonTextMarginLeft = 0;
            this.btn_user_elimiar.ColorContrastOnClick = 45;
            this.btn_user_elimiar.ColorContrastOnHover = 45;
            this.btn_user_elimiar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btn_user_elimiar.CustomizableEdges = borderEdges5;
            this.btn_user_elimiar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_user_elimiar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_user_elimiar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_user_elimiar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_user_elimiar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_user_elimiar.Font = new System.Drawing.Font("Segoe UI Emoji", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_user_elimiar.ForeColor = System.Drawing.Color.White;
            this.btn_user_elimiar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_user_elimiar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_user_elimiar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_user_elimiar.IconMarginLeft = 11;
            this.btn_user_elimiar.IconPadding = 10;
            this.btn_user_elimiar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_user_elimiar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_user_elimiar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_user_elimiar.IconSize = 25;
            this.btn_user_elimiar.IdleBorderColor = System.Drawing.Color.Magenta;
            this.btn_user_elimiar.IdleBorderRadius = 15;
            this.btn_user_elimiar.IdleBorderThickness = 3;
            this.btn_user_elimiar.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btn_user_elimiar.IdleIconLeftImage = global::ProyectoTallerII.Properties.Resources.remove_ico__1_;
            this.btn_user_elimiar.IdleIconRightImage = null;
            this.btn_user_elimiar.IndicateFocus = false;
            this.btn_user_elimiar.Location = new System.Drawing.Point(538, 144);
            this.btn_user_elimiar.Name = "btn_user_elimiar";
            this.btn_user_elimiar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_user_elimiar.OnDisabledState.BorderRadius = 15;
            this.btn_user_elimiar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_elimiar.OnDisabledState.BorderThickness = 3;
            this.btn_user_elimiar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_user_elimiar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_user_elimiar.OnDisabledState.IconLeftImage = null;
            this.btn_user_elimiar.OnDisabledState.IconRightImage = null;
            this.btn_user_elimiar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_user_elimiar.onHoverState.BorderRadius = 15;
            this.btn_user_elimiar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_elimiar.onHoverState.BorderThickness = 3;
            this.btn_user_elimiar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_user_elimiar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_user_elimiar.onHoverState.IconLeftImage = null;
            this.btn_user_elimiar.onHoverState.IconRightImage = null;
            this.btn_user_elimiar.OnIdleState.BorderColor = System.Drawing.Color.Magenta;
            this.btn_user_elimiar.OnIdleState.BorderRadius = 15;
            this.btn_user_elimiar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_elimiar.OnIdleState.BorderThickness = 3;
            this.btn_user_elimiar.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btn_user_elimiar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_user_elimiar.OnIdleState.IconLeftImage = global::ProyectoTallerII.Properties.Resources.remove_ico__1_;
            this.btn_user_elimiar.OnIdleState.IconRightImage = null;
            this.btn_user_elimiar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_user_elimiar.OnPressedState.BorderRadius = 15;
            this.btn_user_elimiar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_user_elimiar.OnPressedState.BorderThickness = 3;
            this.btn_user_elimiar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_user_elimiar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_user_elimiar.OnPressedState.IconLeftImage = null;
            this.btn_user_elimiar.OnPressedState.IconRightImage = null;
            this.btn_user_elimiar.Size = new System.Drawing.Size(150, 39);
            this.btn_user_elimiar.TabIndex = 26;
            this.btn_user_elimiar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_user_elimiar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_user_elimiar.TextMarginLeft = 0;
            this.btn_user_elimiar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_user_elimiar.UseDefaultRadiusAndThickness = true;
            // 
            // txt_stock
            // 
            this.txt_stock.AcceptsReturn = false;
            this.txt_stock.AcceptsTab = false;
            this.txt_stock.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txt_stock.AnimationSpeed = 200;
            this.txt_stock.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_stock.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_stock.BackColor = System.Drawing.Color.Transparent;
            this.txt_stock.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_stock.BackgroundImage")));
            this.txt_stock.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_stock.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_stock.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_stock.BorderColorIdle = System.Drawing.Color.Magenta;
            this.txt_stock.BorderRadius = 20;
            this.txt_stock.BorderThickness = 2;
            this.txt_stock.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_stock.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_stock.DefaultFont = new System.Drawing.Font("Segoe UI", 10F);
            this.txt_stock.DefaultText = "";
            this.txt_stock.FillColor = System.Drawing.SystemColors.ButtonFace;
            this.txt_stock.HideSelection = true;
            this.txt_stock.IconLeft = null;
            this.txt_stock.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_stock.IconPadding = 10;
            this.txt_stock.IconRight = null;
            this.txt_stock.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_stock.Lines = new string[0];
            this.txt_stock.Location = new System.Drawing.Point(29, 119);
            this.txt_stock.MaxLength = 32767;
            this.txt_stock.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_stock.Modified = false;
            this.txt_stock.Multiline = false;
            this.txt_stock.Name = "txt_stock";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_stock.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_stock.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_stock.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Magenta;
            stateProperties32.FillColor = System.Drawing.SystemColors.ButtonFace;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_stock.OnIdleState = stateProperties32;
            this.txt_stock.Padding = new System.Windows.Forms.Padding(3);
            this.txt_stock.PasswordChar = '\0';
            this.txt_stock.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txt_stock.PlaceholderText = "Stock";
            this.txt_stock.ReadOnly = false;
            this.txt_stock.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_stock.SelectedText = "";
            this.txt_stock.SelectionLength = 0;
            this.txt_stock.SelectionStart = 0;
            this.txt_stock.ShortcutsEnabled = true;
            this.txt_stock.Size = new System.Drawing.Size(198, 38);
            this.txt_stock.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_stock.TabIndex = 3;
            this.txt_stock.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_stock.TextMarginBottom = 0;
            this.txt_stock.TextMarginLeft = 3;
            this.txt_stock.TextMarginTop = 0;
            this.txt_stock.TextPlaceholder = "Stock";
            this.txt_stock.UseSystemPasswordChar = false;
            this.txt_stock.WordWrap = true;
            this.txt_stock.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_stock_KeyPress);
            // 
            // lbl_producto_stock
            // 
            this.lbl_producto_stock.AllowParentOverrides = false;
            this.lbl_producto_stock.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.lbl_producto_stock.AutoEllipsis = false;
            this.lbl_producto_stock.Cursor = System.Windows.Forms.Cursors.Default;
            this.lbl_producto_stock.CursorType = System.Windows.Forms.Cursors.Default;
            this.lbl_producto_stock.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.lbl_producto_stock.Location = new System.Drawing.Point(29, 124);
            this.lbl_producto_stock.Name = "lbl_producto_stock";
            this.lbl_producto_stock.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lbl_producto_stock.Size = new System.Drawing.Size(38, 21);
            this.lbl_producto_stock.TabIndex = 10;
            this.lbl_producto_stock.Text = "Stock";
            this.lbl_producto_stock.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lbl_producto_stock.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // drd_productos_categoria
            // 
            this.drd_productos_categoria.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.drd_productos_categoria.BackColor = System.Drawing.Color.Transparent;
            this.drd_productos_categoria.BackgroundColor = System.Drawing.SystemColors.ButtonFace;
            this.drd_productos_categoria.BorderColor = System.Drawing.Color.Magenta;
            this.drd_productos_categoria.BorderRadius = 17;
            this.drd_productos_categoria.Color = System.Drawing.Color.Magenta;
            this.drd_productos_categoria.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.drd_productos_categoria.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.drd_productos_categoria.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.drd_productos_categoria.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.drd_productos_categoria.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.drd_productos_categoria.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.drd_productos_categoria.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.drd_productos_categoria.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.drd_productos_categoria.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.drd_productos_categoria.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.drd_productos_categoria.FillDropDown = true;
            this.drd_productos_categoria.FillIndicator = false;
            this.drd_productos_categoria.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.drd_productos_categoria.Font = new System.Drawing.Font("Segoe UI Emoji", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.drd_productos_categoria.ForeColor = System.Drawing.Color.Black;
            this.drd_productos_categoria.FormattingEnabled = true;
            this.drd_productos_categoria.Icon = null;
            this.drd_productos_categoria.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.drd_productos_categoria.IndicatorColor = System.Drawing.Color.Gray;
            this.drd_productos_categoria.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.drd_productos_categoria.ItemBackColor = System.Drawing.Color.White;
            this.drd_productos_categoria.ItemBorderColor = System.Drawing.Color.White;
            this.drd_productos_categoria.ItemForeColor = System.Drawing.Color.Black;
            this.drd_productos_categoria.ItemHeight = 26;
            this.drd_productos_categoria.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.drd_productos_categoria.ItemHighLightForeColor = System.Drawing.Color.White;
            this.drd_productos_categoria.Items.AddRange(new object[] {
            "Anillos",
            "Alianzas",
            "Aros",
            "Colgantes",
            "Pendientes",
            "Pulseras"});
            this.drd_productos_categoria.ItemTopMargin = 3;
            this.drd_productos_categoria.Location = new System.Drawing.Point(276, 31);
            this.drd_productos_categoria.Name = "drd_productos_categoria";
            this.drd_productos_categoria.Size = new System.Drawing.Size(198, 32);
            this.drd_productos_categoria.TabIndex = 6;
            this.drd_productos_categoria.Text = "Categoría";
            this.drd_productos_categoria.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.drd_productos_categoria.TextLeftMargin = 5;
            // 
            // btn_stock_modificar
            // 
            this.btn_stock_modificar.AllowAnimations = true;
            this.btn_stock_modificar.AllowMouseEffects = true;
            this.btn_stock_modificar.AllowToggling = false;
            this.btn_stock_modificar.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btn_stock_modificar.AnimationSpeed = 200;
            this.btn_stock_modificar.AutoGenerateColors = false;
            this.btn_stock_modificar.AutoRoundBorders = false;
            this.btn_stock_modificar.AutoSizeLeftIcon = true;
            this.btn_stock_modificar.AutoSizeRightIcon = true;
            this.btn_stock_modificar.BackColor = System.Drawing.Color.Transparent;
            this.btn_stock_modificar.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btn_stock_modificar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_stock_modificar.BackgroundImage")));
            this.btn_stock_modificar.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.btn_stock_modificar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_stock_modificar.ButtonText = "Modificar";
            this.btn_stock_modificar.ButtonTextMarginLeft = 0;
            this.btn_stock_modificar.ColorContrastOnClick = 45;
            this.btn_stock_modificar.ColorContrastOnHover = 45;
            this.btn_stock_modificar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btn_stock_modificar.CustomizableEdges = borderEdges6;
            this.btn_stock_modificar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_stock_modificar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_stock_modificar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_stock_modificar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_stock_modificar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_stock_modificar.Font = new System.Drawing.Font("Segoe UI Emoji", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_stock_modificar.ForeColor = System.Drawing.Color.White;
            this.btn_stock_modificar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_stock_modificar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_stock_modificar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_stock_modificar.IconMarginLeft = 11;
            this.btn_stock_modificar.IconPadding = 10;
            this.btn_stock_modificar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_stock_modificar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_stock_modificar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_stock_modificar.IconSize = 25;
            this.btn_stock_modificar.IdleBorderColor = System.Drawing.Color.Magenta;
            this.btn_stock_modificar.IdleBorderRadius = 15;
            this.btn_stock_modificar.IdleBorderThickness = 3;
            this.btn_stock_modificar.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btn_stock_modificar.IdleIconLeftImage = global::ProyectoTallerII.Properties.Resources.ui_settings__1_;
            this.btn_stock_modificar.IdleIconRightImage = null;
            this.btn_stock_modificar.IndicateFocus = false;
            this.btn_stock_modificar.Location = new System.Drawing.Point(538, 54);
            this.btn_stock_modificar.Name = "btn_stock_modificar";
            this.btn_stock_modificar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_stock_modificar.OnDisabledState.BorderRadius = 15;
            this.btn_stock_modificar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_stock_modificar.OnDisabledState.BorderThickness = 3;
            this.btn_stock_modificar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_stock_modificar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_stock_modificar.OnDisabledState.IconLeftImage = null;
            this.btn_stock_modificar.OnDisabledState.IconRightImage = null;
            this.btn_stock_modificar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_stock_modificar.onHoverState.BorderRadius = 15;
            this.btn_stock_modificar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_stock_modificar.onHoverState.BorderThickness = 3;
            this.btn_stock_modificar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_stock_modificar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_stock_modificar.onHoverState.IconLeftImage = null;
            this.btn_stock_modificar.onHoverState.IconRightImage = null;
            this.btn_stock_modificar.OnIdleState.BorderColor = System.Drawing.Color.Magenta;
            this.btn_stock_modificar.OnIdleState.BorderRadius = 15;
            this.btn_stock_modificar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_stock_modificar.OnIdleState.BorderThickness = 3;
            this.btn_stock_modificar.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btn_stock_modificar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_stock_modificar.OnIdleState.IconLeftImage = global::ProyectoTallerII.Properties.Resources.ui_settings__1_;
            this.btn_stock_modificar.OnIdleState.IconRightImage = null;
            this.btn_stock_modificar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_stock_modificar.OnPressedState.BorderRadius = 15;
            this.btn_stock_modificar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_stock_modificar.OnPressedState.BorderThickness = 3;
            this.btn_stock_modificar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_stock_modificar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_stock_modificar.OnPressedState.IconLeftImage = null;
            this.btn_stock_modificar.OnPressedState.IconRightImage = null;
            this.btn_stock_modificar.Size = new System.Drawing.Size(150, 39);
            this.btn_stock_modificar.TabIndex = 15;
            this.btn_stock_modificar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_stock_modificar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_stock_modificar.TextMarginLeft = 0;
            this.btn_stock_modificar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_stock_modificar.UseDefaultRadiusAndThickness = true;
            this.btn_stock_modificar.Click += new System.EventHandler(this.btn_stock_modificar_Click);
            // 
            // btn_stock_limpiar
            // 
            this.btn_stock_limpiar.AllowAnimations = true;
            this.btn_stock_limpiar.AllowMouseEffects = true;
            this.btn_stock_limpiar.AllowToggling = false;
            this.btn_stock_limpiar.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btn_stock_limpiar.AnimationSpeed = 200;
            this.btn_stock_limpiar.AutoGenerateColors = false;
            this.btn_stock_limpiar.AutoRoundBorders = false;
            this.btn_stock_limpiar.AutoSizeLeftIcon = true;
            this.btn_stock_limpiar.AutoSizeRightIcon = true;
            this.btn_stock_limpiar.BackColor = System.Drawing.Color.Transparent;
            this.btn_stock_limpiar.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btn_stock_limpiar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_stock_limpiar.BackgroundImage")));
            this.btn_stock_limpiar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_stock_limpiar.ButtonText = "Limpiar";
            this.btn_stock_limpiar.ButtonTextMarginLeft = 0;
            this.btn_stock_limpiar.ColorContrastOnClick = 45;
            this.btn_stock_limpiar.ColorContrastOnHover = 45;
            this.btn_stock_limpiar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btn_stock_limpiar.CustomizableEdges = borderEdges7;
            this.btn_stock_limpiar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_stock_limpiar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_stock_limpiar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_stock_limpiar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_stock_limpiar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_stock_limpiar.Font = new System.Drawing.Font("Segoe UI Emoji", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_stock_limpiar.ForeColor = System.Drawing.Color.White;
            this.btn_stock_limpiar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_stock_limpiar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_stock_limpiar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_stock_limpiar.IconMarginLeft = 11;
            this.btn_stock_limpiar.IconPadding = 10;
            this.btn_stock_limpiar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_stock_limpiar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_stock_limpiar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_stock_limpiar.IconSize = 25;
            this.btn_stock_limpiar.IdleBorderColor = System.Drawing.Color.Magenta;
            this.btn_stock_limpiar.IdleBorderRadius = 15;
            this.btn_stock_limpiar.IdleBorderThickness = 3;
            this.btn_stock_limpiar.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btn_stock_limpiar.IdleIconLeftImage = global::ProyectoTallerII.Properties.Resources.eraser__1_;
            this.btn_stock_limpiar.IdleIconRightImage = null;
            this.btn_stock_limpiar.IndicateFocus = false;
            this.btn_stock_limpiar.Location = new System.Drawing.Point(538, 99);
            this.btn_stock_limpiar.Name = "btn_stock_limpiar";
            this.btn_stock_limpiar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_stock_limpiar.OnDisabledState.BorderRadius = 15;
            this.btn_stock_limpiar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_stock_limpiar.OnDisabledState.BorderThickness = 3;
            this.btn_stock_limpiar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_stock_limpiar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_stock_limpiar.OnDisabledState.IconLeftImage = null;
            this.btn_stock_limpiar.OnDisabledState.IconRightImage = null;
            this.btn_stock_limpiar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_stock_limpiar.onHoverState.BorderRadius = 15;
            this.btn_stock_limpiar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_stock_limpiar.onHoverState.BorderThickness = 3;
            this.btn_stock_limpiar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_stock_limpiar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_stock_limpiar.onHoverState.IconLeftImage = null;
            this.btn_stock_limpiar.onHoverState.IconRightImage = null;
            this.btn_stock_limpiar.OnIdleState.BorderColor = System.Drawing.Color.Magenta;
            this.btn_stock_limpiar.OnIdleState.BorderRadius = 15;
            this.btn_stock_limpiar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_stock_limpiar.OnIdleState.BorderThickness = 3;
            this.btn_stock_limpiar.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btn_stock_limpiar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_stock_limpiar.OnIdleState.IconLeftImage = global::ProyectoTallerII.Properties.Resources.eraser__1_;
            this.btn_stock_limpiar.OnIdleState.IconRightImage = null;
            this.btn_stock_limpiar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_stock_limpiar.OnPressedState.BorderRadius = 15;
            this.btn_stock_limpiar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_stock_limpiar.OnPressedState.BorderThickness = 3;
            this.btn_stock_limpiar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_stock_limpiar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_stock_limpiar.OnPressedState.IconLeftImage = null;
            this.btn_stock_limpiar.OnPressedState.IconRightImage = null;
            this.btn_stock_limpiar.Size = new System.Drawing.Size(150, 39);
            this.btn_stock_limpiar.TabIndex = 14;
            this.btn_stock_limpiar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_stock_limpiar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_stock_limpiar.TextMarginLeft = 0;
            this.btn_stock_limpiar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_stock_limpiar.UseDefaultRadiusAndThickness = true;
            this.btn_stock_limpiar.Click += new System.EventHandler(this.btn_stock_limpiar_Click);
            // 
            // txt_producto_cod
            // 
            this.txt_producto_cod.AcceptsReturn = false;
            this.txt_producto_cod.AcceptsTab = false;
            this.txt_producto_cod.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txt_producto_cod.AnimationSpeed = 200;
            this.txt_producto_cod.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_producto_cod.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_producto_cod.BackColor = System.Drawing.Color.Transparent;
            this.txt_producto_cod.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_producto_cod.BackgroundImage")));
            this.txt_producto_cod.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_producto_cod.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_producto_cod.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_producto_cod.BorderColorIdle = System.Drawing.Color.Magenta;
            this.txt_producto_cod.BorderRadius = 20;
            this.txt_producto_cod.BorderThickness = 2;
            this.txt_producto_cod.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_producto_cod.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_producto_cod.DefaultFont = new System.Drawing.Font("Segoe UI", 10F);
            this.txt_producto_cod.DefaultText = "";
            this.txt_producto_cod.FillColor = System.Drawing.SystemColors.ButtonFace;
            this.txt_producto_cod.ForeColor = System.Drawing.SystemColors.ControlText;
            this.txt_producto_cod.HideSelection = true;
            this.txt_producto_cod.IconLeft = null;
            this.txt_producto_cod.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_producto_cod.IconPadding = 10;
            this.txt_producto_cod.IconRight = null;
            this.txt_producto_cod.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_producto_cod.Lines = new string[0];
            this.txt_producto_cod.Location = new System.Drawing.Point(29, 31);
            this.txt_producto_cod.MaxLength = 16;
            this.txt_producto_cod.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_producto_cod.Modified = false;
            this.txt_producto_cod.Multiline = false;
            this.txt_producto_cod.Name = "txt_producto_cod";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_producto_cod.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_producto_cod.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_producto_cod.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Magenta;
            stateProperties36.FillColor = System.Drawing.SystemColors.ButtonFace;
            stateProperties36.ForeColor = System.Drawing.SystemColors.ControlText;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_producto_cod.OnIdleState = stateProperties36;
            this.txt_producto_cod.Padding = new System.Windows.Forms.Padding(3);
            this.txt_producto_cod.PasswordChar = '\0';
            this.txt_producto_cod.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txt_producto_cod.PlaceholderText = "Cod. Producto";
            this.txt_producto_cod.ReadOnly = false;
            this.txt_producto_cod.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_producto_cod.SelectedText = "";
            this.txt_producto_cod.SelectionLength = 0;
            this.txt_producto_cod.SelectionStart = 0;
            this.txt_producto_cod.ShortcutsEnabled = true;
            this.txt_producto_cod.Size = new System.Drawing.Size(198, 38);
            this.txt_producto_cod.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_producto_cod.TabIndex = 1;
            this.txt_producto_cod.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_producto_cod.TextMarginBottom = 0;
            this.txt_producto_cod.TextMarginLeft = 3;
            this.txt_producto_cod.TextMarginTop = 0;
            this.txt_producto_cod.TextPlaceholder = "Cod. Producto";
            this.txt_producto_cod.UseSystemPasswordChar = false;
            this.txt_producto_cod.WordWrap = true;
            this.txt_producto_cod.TextChanged += new System.EventHandler(this.txt_producto_cod_TextChanged);
            this.txt_producto_cod.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_producto_cod_KeyPress);
            // 
            // txt_producto_nombre
            // 
            this.txt_producto_nombre.AcceptsReturn = false;
            this.txt_producto_nombre.AcceptsTab = false;
            this.txt_producto_nombre.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txt_producto_nombre.AnimationSpeed = 200;
            this.txt_producto_nombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_producto_nombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_producto_nombre.BackColor = System.Drawing.Color.Transparent;
            this.txt_producto_nombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_producto_nombre.BackgroundImage")));
            this.txt_producto_nombre.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_producto_nombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_producto_nombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_producto_nombre.BorderColorIdle = System.Drawing.Color.Magenta;
            this.txt_producto_nombre.BorderRadius = 20;
            this.txt_producto_nombre.BorderThickness = 2;
            this.txt_producto_nombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_producto_nombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_producto_nombre.DefaultFont = new System.Drawing.Font("Segoe UI", 10F);
            this.txt_producto_nombre.DefaultText = "";
            this.txt_producto_nombre.FillColor = System.Drawing.SystemColors.ButtonFace;
            this.txt_producto_nombre.HideSelection = true;
            this.txt_producto_nombre.IconLeft = null;
            this.txt_producto_nombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_producto_nombre.IconPadding = 10;
            this.txt_producto_nombre.IconRight = null;
            this.txt_producto_nombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_producto_nombre.Lines = new string[0];
            this.txt_producto_nombre.Location = new System.Drawing.Point(29, 75);
            this.txt_producto_nombre.MaxLength = 32767;
            this.txt_producto_nombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_producto_nombre.Modified = false;
            this.txt_producto_nombre.Multiline = false;
            this.txt_producto_nombre.Name = "txt_producto_nombre";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_producto_nombre.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_producto_nombre.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_producto_nombre.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Magenta;
            stateProperties40.FillColor = System.Drawing.SystemColors.ButtonFace;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_producto_nombre.OnIdleState = stateProperties40;
            this.txt_producto_nombre.Padding = new System.Windows.Forms.Padding(3);
            this.txt_producto_nombre.PasswordChar = '\0';
            this.txt_producto_nombre.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txt_producto_nombre.PlaceholderText = "Nombre Producto";
            this.txt_producto_nombre.ReadOnly = false;
            this.txt_producto_nombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_producto_nombre.SelectedText = "";
            this.txt_producto_nombre.SelectionLength = 0;
            this.txt_producto_nombre.SelectionStart = 0;
            this.txt_producto_nombre.ShortcutsEnabled = true;
            this.txt_producto_nombre.Size = new System.Drawing.Size(198, 38);
            this.txt_producto_nombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_producto_nombre.TabIndex = 2;
            this.txt_producto_nombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_producto_nombre.TextMarginBottom = 0;
            this.txt_producto_nombre.TextMarginLeft = 3;
            this.txt_producto_nombre.TextMarginTop = 0;
            this.txt_producto_nombre.TextPlaceholder = "Nombre Producto";
            this.txt_producto_nombre.UseSystemPasswordChar = false;
            this.txt_producto_nombre.WordWrap = true;
            this.txt_producto_nombre.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_producto_nombre_KeyPress);
            // 
            // txt_producto_costo
            // 
            this.txt_producto_costo.AcceptsReturn = false;
            this.txt_producto_costo.AcceptsTab = false;
            this.txt_producto_costo.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txt_producto_costo.AnimationSpeed = 200;
            this.txt_producto_costo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_producto_costo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_producto_costo.BackColor = System.Drawing.Color.Transparent;
            this.txt_producto_costo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_producto_costo.BackgroundImage")));
            this.txt_producto_costo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_producto_costo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_producto_costo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_producto_costo.BorderColorIdle = System.Drawing.Color.Magenta;
            this.txt_producto_costo.BorderRadius = 20;
            this.txt_producto_costo.BorderThickness = 2;
            this.txt_producto_costo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_producto_costo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_producto_costo.DefaultFont = new System.Drawing.Font("Segoe UI", 10F);
            this.txt_producto_costo.DefaultText = "";
            this.txt_producto_costo.FillColor = System.Drawing.SystemColors.ButtonFace;
            this.txt_producto_costo.HideSelection = true;
            this.txt_producto_costo.IconLeft = null;
            this.txt_producto_costo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_producto_costo.IconPadding = 10;
            this.txt_producto_costo.IconRight = null;
            this.txt_producto_costo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_producto_costo.Lines = new string[0];
            this.txt_producto_costo.Location = new System.Drawing.Point(276, 75);
            this.txt_producto_costo.MaxLength = 32767;
            this.txt_producto_costo.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_producto_costo.Modified = false;
            this.txt_producto_costo.Multiline = false;
            this.txt_producto_costo.Name = "txt_producto_costo";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_producto_costo.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_producto_costo.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_producto_costo.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Magenta;
            stateProperties44.FillColor = System.Drawing.SystemColors.ButtonFace;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_producto_costo.OnIdleState = stateProperties44;
            this.txt_producto_costo.Padding = new System.Windows.Forms.Padding(3);
            this.txt_producto_costo.PasswordChar = '\0';
            this.txt_producto_costo.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txt_producto_costo.PlaceholderText = "Percio Costo";
            this.txt_producto_costo.ReadOnly = false;
            this.txt_producto_costo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_producto_costo.SelectedText = "";
            this.txt_producto_costo.SelectionLength = 0;
            this.txt_producto_costo.SelectionStart = 0;
            this.txt_producto_costo.ShortcutsEnabled = true;
            this.txt_producto_costo.Size = new System.Drawing.Size(198, 38);
            this.txt_producto_costo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_producto_costo.TabIndex = 4;
            this.txt_producto_costo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_producto_costo.TextMarginBottom = 0;
            this.txt_producto_costo.TextMarginLeft = 3;
            this.txt_producto_costo.TextMarginTop = 0;
            this.txt_producto_costo.TextPlaceholder = "Percio Costo";
            this.txt_producto_costo.UseSystemPasswordChar = false;
            this.txt_producto_costo.WordWrap = true;
            this.txt_producto_costo.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_producto_costo_KeyPress);
            // 
            // btn_stock_agregar
            // 
            this.btn_stock_agregar.AllowAnimations = true;
            this.btn_stock_agregar.AllowMouseEffects = true;
            this.btn_stock_agregar.AllowToggling = false;
            this.btn_stock_agregar.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btn_stock_agregar.AnimationSpeed = 200;
            this.btn_stock_agregar.AutoGenerateColors = false;
            this.btn_stock_agregar.AutoRoundBorders = false;
            this.btn_stock_agregar.AutoSizeLeftIcon = true;
            this.btn_stock_agregar.AutoSizeRightIcon = true;
            this.btn_stock_agregar.BackColor = System.Drawing.Color.Transparent;
            this.btn_stock_agregar.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btn_stock_agregar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_stock_agregar.BackgroundImage")));
            this.btn_stock_agregar.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.btn_stock_agregar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_stock_agregar.ButtonText = "Guardar";
            this.btn_stock_agregar.ButtonTextMarginLeft = 0;
            this.btn_stock_agregar.ColorContrastOnClick = 45;
            this.btn_stock_agregar.ColorContrastOnHover = 45;
            this.btn_stock_agregar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btn_stock_agregar.CustomizableEdges = borderEdges8;
            this.btn_stock_agregar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_stock_agregar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_stock_agregar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_stock_agregar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_stock_agregar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_stock_agregar.Font = new System.Drawing.Font("Segoe UI Emoji", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_stock_agregar.ForeColor = System.Drawing.Color.White;
            this.btn_stock_agregar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_stock_agregar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_stock_agregar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_stock_agregar.IconMarginLeft = 11;
            this.btn_stock_agregar.IconPadding = 10;
            this.btn_stock_agregar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_stock_agregar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_stock_agregar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_stock_agregar.IconSize = 25;
            this.btn_stock_agregar.IdleBorderColor = System.Drawing.Color.Magenta;
            this.btn_stock_agregar.IdleBorderRadius = 15;
            this.btn_stock_agregar.IdleBorderThickness = 3;
            this.btn_stock_agregar.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btn_stock_agregar.IdleIconLeftImage = global::ProyectoTallerII.Properties.Resources.save__1_;
            this.btn_stock_agregar.IdleIconRightImage = null;
            this.btn_stock_agregar.IndicateFocus = false;
            this.btn_stock_agregar.Location = new System.Drawing.Point(538, 9);
            this.btn_stock_agregar.Name = "btn_stock_agregar";
            this.btn_stock_agregar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_stock_agregar.OnDisabledState.BorderRadius = 15;
            this.btn_stock_agregar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_stock_agregar.OnDisabledState.BorderThickness = 3;
            this.btn_stock_agregar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_stock_agregar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_stock_agregar.OnDisabledState.IconLeftImage = null;
            this.btn_stock_agregar.OnDisabledState.IconRightImage = null;
            this.btn_stock_agregar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_stock_agregar.onHoverState.BorderRadius = 15;
            this.btn_stock_agregar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_stock_agregar.onHoverState.BorderThickness = 3;
            this.btn_stock_agregar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_stock_agregar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_stock_agregar.onHoverState.IconLeftImage = null;
            this.btn_stock_agregar.onHoverState.IconRightImage = null;
            this.btn_stock_agregar.OnIdleState.BorderColor = System.Drawing.Color.Magenta;
            this.btn_stock_agregar.OnIdleState.BorderRadius = 15;
            this.btn_stock_agregar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_stock_agregar.OnIdleState.BorderThickness = 3;
            this.btn_stock_agregar.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btn_stock_agregar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_stock_agregar.OnIdleState.IconLeftImage = global::ProyectoTallerII.Properties.Resources.save__1_;
            this.btn_stock_agregar.OnIdleState.IconRightImage = null;
            this.btn_stock_agregar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_stock_agregar.OnPressedState.BorderRadius = 15;
            this.btn_stock_agregar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_stock_agregar.OnPressedState.BorderThickness = 3;
            this.btn_stock_agregar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_stock_agregar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_stock_agregar.OnPressedState.IconLeftImage = null;
            this.btn_stock_agregar.OnPressedState.IconRightImage = null;
            this.btn_stock_agregar.Size = new System.Drawing.Size(150, 39);
            this.btn_stock_agregar.TabIndex = 11;
            this.btn_stock_agregar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_stock_agregar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_stock_agregar.TextMarginLeft = 0;
            this.btn_stock_agregar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_stock_agregar.UseDefaultRadiusAndThickness = true;
            this.btn_stock_agregar.Click += new System.EventHandler(this.btn_stock_agregar_Click);
            // 
            // txt_producto_venta
            // 
            this.txt_producto_venta.AcceptsReturn = false;
            this.txt_producto_venta.AcceptsTab = false;
            this.txt_producto_venta.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txt_producto_venta.AnimationSpeed = 200;
            this.txt_producto_venta.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_producto_venta.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_producto_venta.BackColor = System.Drawing.Color.Transparent;
            this.txt_producto_venta.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_producto_venta.BackgroundImage")));
            this.txt_producto_venta.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_producto_venta.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_producto_venta.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_producto_venta.BorderColorIdle = System.Drawing.Color.Magenta;
            this.txt_producto_venta.BorderRadius = 20;
            this.txt_producto_venta.BorderThickness = 2;
            this.txt_producto_venta.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_producto_venta.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_producto_venta.DefaultFont = new System.Drawing.Font("Segoe UI", 10F);
            this.txt_producto_venta.DefaultText = "";
            this.txt_producto_venta.FillColor = System.Drawing.SystemColors.ButtonFace;
            this.txt_producto_venta.HideSelection = true;
            this.txt_producto_venta.IconLeft = null;
            this.txt_producto_venta.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_producto_venta.IconPadding = 10;
            this.txt_producto_venta.IconRight = null;
            this.txt_producto_venta.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_producto_venta.Lines = new string[0];
            this.txt_producto_venta.Location = new System.Drawing.Point(276, 119);
            this.txt_producto_venta.MaxLength = 32767;
            this.txt_producto_venta.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_producto_venta.Modified = false;
            this.txt_producto_venta.Multiline = false;
            this.txt_producto_venta.Name = "txt_producto_venta";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_producto_venta.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_producto_venta.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_producto_venta.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Magenta;
            stateProperties48.FillColor = System.Drawing.SystemColors.ButtonFace;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_producto_venta.OnIdleState = stateProperties48;
            this.txt_producto_venta.Padding = new System.Windows.Forms.Padding(3);
            this.txt_producto_venta.PasswordChar = '\0';
            this.txt_producto_venta.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.txt_producto_venta.PlaceholderText = "Precio Venta";
            this.txt_producto_venta.ReadOnly = false;
            this.txt_producto_venta.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_producto_venta.SelectedText = "";
            this.txt_producto_venta.SelectionLength = 0;
            this.txt_producto_venta.SelectionStart = 0;
            this.txt_producto_venta.ShortcutsEnabled = true;
            this.txt_producto_venta.Size = new System.Drawing.Size(198, 38);
            this.txt_producto_venta.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_producto_venta.TabIndex = 5;
            this.txt_producto_venta.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_producto_venta.TextMarginBottom = 0;
            this.txt_producto_venta.TextMarginLeft = 3;
            this.txt_producto_venta.TextMarginTop = 0;
            this.txt_producto_venta.TextPlaceholder = "Precio Venta";
            this.txt_producto_venta.UseSystemPasswordChar = false;
            this.txt_producto_venta.WordWrap = true;
            this.txt_producto_venta.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txt_producto_venta_KeyPress);
            // 
            // dtg_stock
            // 
            this.dtg_stock.AllowUserToAddRows = false;
            this.dtg_stock.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.dtg_stock.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.AllCells;
            this.dtg_stock.AutoSizeRowsMode = System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
            this.dtg_stock.BackgroundColor = System.Drawing.Color.DarkSlateBlue;
            this.dtg_stock.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dtg_stock.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dtg_stock.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
            dataGridViewCellStyle4.Alignment = System.Windows.Forms.DataGridViewContentAlignment.TopCenter;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.Blue;
            dataGridViewCellStyle4.Font = new System.Drawing.Font("Segoe UI Emoji", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle4.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle4.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle4.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dtg_stock.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle4;
            this.dtg_stock.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dtg_stock.EnableHeadersVisualStyles = false;
            this.dtg_stock.GridColor = System.Drawing.Color.GreenYellow;
            this.dtg_stock.Location = new System.Drawing.Point(33, 351);
            this.dtg_stock.Name = "dtg_stock";
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dtg_stock.RowHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.dtg_stock.RowHeadersVisible = false;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle6.BackColor = System.Drawing.Color.DarkSlateBlue;
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Segoe UI Emoji", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.Color.DeepSkyBlue;
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.Color.Yellow;
            this.dtg_stock.RowsDefaultCellStyle = dataGridViewCellStyle6;
            this.dtg_stock.Size = new System.Drawing.Size(741, 177);
            this.dtg_stock.TabIndex = 25;
            // 
            // Form_stock
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(802, 527);
            this.Controls.Add(this.dtg_stock);
            this.Controls.Add(this.panel_stock);
            this.Controls.Add(this.pnl_buscador);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Form_stock";
            this.Text = "Form_stock";
            this.Load += new System.EventHandler(this.Form_stock_Load);
            this.pnl_buscador.ResumeLayout(false);
            this.pnl_buscador.PerformLayout();
            this.panel_stock.ResumeLayout(false);
            this.panel_stock.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dtg_stock)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel pnl_buscador;
        private System.Windows.Forms.Button button1;
        private Bunifu.UI.WinForms.BunifuLabel lbl_stock_title;
        private Bunifu.UI.WinForms.BunifuTextBox txt_buscar;
        private Bunifu.UI.WinForms.BunifuPanel panel_stock;
        private Bunifu.UI.WinForms.BunifuDropdown drd_productos_categoria;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_stock_modificar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_stock_limpiar;
        private Bunifu.UI.WinForms.BunifuTextBox txt_producto_cod;
        private Bunifu.UI.WinForms.BunifuTextBox txt_producto_nombre;
        private Bunifu.UI.WinForms.BunifuTextBox txt_producto_costo;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_stock_agregar;
        private Bunifu.UI.WinForms.BunifuTextBox txt_producto_venta;
        private Bunifu.UI.WinForms.BunifuLabel lbl_producto_stock;
        private Bunifu.UI.WinForms.BunifuTextBox txt_stock;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_user_elimiar;
        private System.Windows.Forms.DataGridView dtg_stock;
    }
}